In [1]:
import pandas as pd

### Web Scraping accredited online schools

In [2]:
url = 'https://www.guidetoonlineschools.com/online-schools?f_show=all'

In [3]:
tables = pd.read_html(url)
tables
upper_df=pd.Series

In [4]:
len(tables)

11

In [5]:
type(tables)

list

In [6]:
df = tables[4]
#df.columns = ['School', 'Annual Tuition', 'Recommend Rate']
df.head()

                         School Annual Tuition    Recommend Rate
0  Abilene Christian University        $33,330  100% (6 reviews)
1    Abraham Lincoln University         $7,500  100% (2 reviews)
2        Adams State University        $20,456   50% (2 reviews)
3            Adelphi University        $37,170        Add Review
4           Alvernia University        $33,640        Add Review

In [7]:
strip_df = df.columns
strip2_df= df[strip_df].replace({' ':''}, regex = True)
strip2_df.head()

                       School Annual Tuition  Recommend Rate
0  AbileneChristianUniversity        $33,330  100%(6reviews)
1    AbrahamLincolnUniversity         $7,500  100%(2reviews)
2        AdamsStateUniversity        $20,456   50%(2reviews)
3           AdelphiUniversity        $37,170       AddReview
4          AlverniaUniversity        $33,640       AddReview

In [8]:
strip2_df["School"]=strip2_df["School"].apply(str.upper)
strip2_df.head()

                       School Annual Tuition  Recommend Rate
0  ABILENECHRISTIANUNIVERSITY        $33,330  100%(6reviews)
1    ABRAHAMLINCOLNUNIVERSITY         $7,500  100%(2reviews)
2        ADAMSSTATEUNIVERSITY        $20,456   50%(2reviews)
3           ADELPHIUNIVERSITY        $37,170       AddReview
4          ALVERNIAUNIVERSITY        $33,640       AddReview

In [9]:
online_schools_df = strip2_df.drop(columns =["Annual Tuition", "Recommend Rate"])
online_schools_df.head()

                       School
0  ABILENECHRISTIANUNIVERSITY
1    ABRAHAMLINCOLNUNIVERSITY
2        ADAMSSTATEUNIVERSITY
3           ADELPHIUNIVERSITY
4          ALVERNIAUNIVERSITY

In [10]:
online_schools_df['School'] =online_schools_df['School'].str.replace("&","")
online_schools_df['School'] =online_schools_df['School'].str.replace("-","")
online_schools_df['School'] =online_schools_df['School'].str.replace(".","")

In [11]:
online_schools_df['Online'] = "TRUE"
online_schools_df.head()

                       School Online
0  ABILENECHRISTIANUNIVERSITY   TRUE
1    ABRAHAMLINCOLNUNIVERSITY   TRUE
2        ADAMSSTATEUNIVERSITY   TRUE
3           ADELPHIUNIVERSITY   TRUE
4          ALVERNIAUNIVERSITY   TRUE

In [12]:
online_schools_df = online_schools_df.rename(columns={"School":"UP_INSTNM"})
online_schools_df.head()

                    UP_INSTNM Online
0  ABILENECHRISTIANUNIVERSITY   TRUE
1    ABRAHAMLINCOLNUNIVERSITY   TRUE
2        ADAMSSTATEUNIVERSITY   TRUE
3           ADELPHIUNIVERSITY   TRUE
4          ALVERNIAUNIVERSITY   TRUE

In [23]:
online_schools_df.set_index("UP_INSTNM")

                                               Online
UP_INSTNM
ABILENECHRISTIANUNIVERSITY                       TRUE
ABRAHAMLINCOLNUNIVERSITY                         TRUE
ADAMSSTATEUNIVERSITY                             TRUE
ADELPHIUNIVERSITY                                TRUE
ALVERNIAUNIVERSITY                               TRUE
AMERICANINTERCONTINENTALUNIVERSITY               TRUE
AMERICANINTERNATIONALCOLLEGE                     TRUE
AMERICANNATIONALUNIVERSITY                       TRUE
AMERICANPUBLICUNIVERSITYSYSTEM                   TRUE
AMERICANUNIVERSITY                               TRUE
AMERICANUNIVERSITYMBA                            TRUE
ANDERSONUNIVERSITYSC                             TRUE
ANGELOSTATEUNIVERSITY                            TRUE
ANNAMARIACOLLEGE                                 TRUE
ANTIOCHUNIVERSITYONLINE                          TRUE
APPALACHIANSTATEUNIVERSITY                       TRUE
ARCADIAUNIVERSITY                                TRUE
ARIZONASTATEUNIVERSITY                           TRUE
ARKANSASSTATEUNIVERSITY                          TRUE
ASHFORDUNIVERSITY                                TRUE
AUBURNUNIVERSITY                                 TRUE
AUGUSTANAUNIVERSITYSD                            TRUE
AUSTINPEAYSTATEUNIVERSITY                        TRUE
BAKERCOLLEGEONLINE                               TRUE
BALLSTATEUNIVERSITY                              TRUE
THEBAPTISTCOLLEGEOFFLORIDA                       TRUE
BARRYUNIVERSITY                                  TRUE
BAYLORUNIVERSITY                                 TRUE
BELLEVUEUNIVERSITY                               TRUE
BENEDICTINEUNIVERSITY                            TRUE
...                                               ...
VIRGINIAPOLYTECHNICINSTITUTEANDSTATEUNIVERSITY   TRUE
VITERBOUNIVERSITY                                TRUE
WALDENUNIVERSITY                                 TRUE
WALDORFUNIVERSITY                                TRUE
WALSHUNIVERSITY                                  TRUE
WARNERUNIVERSITY                                 TRUE
WASHINGTONSTATEUNIVERSITY                        TRUE
WAYLANDBAPTISTUNIVERSITY                         TRUE
WAYNESTATEUNIVERSITY                             TRUE
WEBSTERUNIVERSITY                                TRUE
WESTCOASTUNIVERSITY                              TRUE
WESTTEXASAMUNIVERSITY                            TRUE
WESTVIRGINIAUNIVERSITY                           TRUE
WESTERNCAROLINAUNIVERSITY                        TRUE
WESTERNGOVERNORSUNIVERSITY                       TRUE
WESTERNILLINOISUNIVERSITY                        TRUE
WESTERNKENTUCKYUNIVERSITY                        TRUE
WESTERNMICHIGANUNIVERSITY                        TRUE
WESTERNNEWENGLANDUNIVERSITY                      TRUE
WESTERNWASHINGTONUNIVERSITY                      TRUE
WHEELINGJESUITUNIVERSITY                         TRUE
WICHITASTATEUNIVERSITY                           TRUE
WIDENERUNIVERSITY                                TRUE
WILKESUNIVERSITY                                 TRUE
WILLIAMCAREYUNIVERSITY                           TRUE
WILLIAMWOODSUNIVERSITY                           TRUE
WINTHROPUNIVERSITY                               TRUE
WRIGHTSTATEUNIVERSITYMAINCAMPUS                  TRUE
YORKCOLLEGE                                      TRUE
YOUNGSTOWNSTATEUNIVERSITY                        TRUE

[567 rows x 1 columns]

In [24]:
online_schools_df.to_csv('Resources/Online-schools.csv')

In [25]:
print(online_schools_df)

                                          UP_INSTNM Online
0                        ABILENECHRISTIANUNIVERSITY   TRUE
1                          ABRAHAMLINCOLNUNIVERSITY   TRUE
2                              ADAMSSTATEUNIVERSITY   TRUE
3                                 ADELPHIUNIVERSITY   TRUE
4                                ALVERNIAUNIVERSITY   TRUE
5                AMERICANINTERCONTINENTALUNIVERSITY   TRUE
6                      AMERICANINTERNATIONALCOLLEGE   TRUE
7                        AMERICANNATIONALUNIVERSITY   TRUE
8                    AMERICANPUBLICUNIVERSITYSYSTEM   TRUE
9                                AMERICANUNIVERSITY   TRUE
10                            AMERICANUNIVERSITYMBA   TRUE
11                             ANDERSONUNIVERSITYSC   TRUE
12                            ANGELOSTATEUNIVERSITY   TRUE
13                                 ANNAMARIACOLLEGE   TRUE
14                          ANTIOCHUNIVERSITYONLINE   TRUE
15                       APPALACHIANSTATEUNIVERSITY   TRUE
16                                ARCADIAUNIVERSITY   TRUE
17                           ARIZONASTATEUNIVERSITY   TRUE
18                          ARKANSASSTATEUNIVERSITY   TRUE
19                                ASHFORDUNIVERSITY   TRUE
20                                 AUBURNUNIVERSITY   TRUE
21                            AUGUSTANAUNIVERSITYSD   TRUE
22                        AUSTINPEAYSTATEUNIVERSITY   TRUE
23                               BAKERCOLLEGEONLINE   TRUE
24                              BALLSTATEUNIVERSITY   TRUE
25                       THEBAPTISTCOLLEGEOFFLORIDA   TRUE
26                                  BARRYUNIVERSITY   TRUE
27                                 BAYLORUNIVERSITY   TRUE
28                               BELLEVUEUNIVERSITY   TRUE
29                            BENEDICTINEUNIVERSITY   TRUE
..                                              ...    ...
537  VIRGINIAPOLYTECHNICINSTITUTEANDSTATEUNIVERSITY   TRUE
538                               VITERBOUNIVERSITY   TRUE
539                                WALDENUNIVERSITY   TRUE
540                               WALDORFUNIVERSITY   TRUE
541                                 WALSHUNIVERSITY   TRUE
542                                WARNERUNIVERSITY   TRUE
543                       WASHINGTONSTATEUNIVERSITY   TRUE
544                        WAYLANDBAPTISTUNIVERSITY   TRUE
545                            WAYNESTATEUNIVERSITY   TRUE
546                               WEBSTERUNIVERSITY   TRUE
547                             WESTCOASTUNIVERSITY   TRUE
548                           WESTTEXASAMUNIVERSITY   TRUE
549                          WESTVIRGINIAUNIVERSITY   TRUE
550                       WESTERNCAROLINAUNIVERSITY   TRUE
551                      WESTERNGOVERNORSUNIVERSITY   TRUE
552                       WESTERNILLINOISUNIVERSITY   TRUE
553                       WESTERNKENTUCKYUNIVERSITY   TRUE
554                       WESTERNMICHIGANUNIVERSITY   TRUE
555                     WESTERNNEWENGLANDUNIVERSITY   TRUE
556                     WESTERNWASHINGTONUNIVERSITY   TRUE
557                        WHEELINGJESUITUNIVERSITY   TRUE
558                          WICHITASTATEUNIVERSITY   TRUE
559                               WIDENERUNIVERSITY   TRUE
560                                WILKESUNIVERSITY   TRUE
561                          WILLIAMCAREYUNIVERSITY   TRUE
562                          WILLIAMWOODSUNIVERSITY   TRUE
563                              WINTHROPUNIVERSITY   TRUE
564                 WRIGHTSTATEUNIVERSITYMAINCAMPUS   TRUE
565                                     YORKCOLLEGE   TRUE
566                       YOUNGSTOWNSTATEUNIVERSITY   TRUE

[567 rows x 2 columns]

In [26]:
online_schools_df.count()

UP_INSTNM    567
Online       567
dtype: int64

### Joining Online Accredited School with All-Data

In [27]:
all_data = "Resources/All-Data.csv"
all_data_df = pd.read_csv(all_data)

In [28]:
#Add column of institution name (Strings only)
all_data_df['UP_INSTNM'] = all_data_df['INSTNM']

In [29]:
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.upper() 
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace(" ","")
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace("-","")
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace("&","")
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace(".","")
all_data_df.head()
# print(all_data_df['UP_INSTNM'])

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP,UP_INSTNM
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.2645,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852,ALABAMAAMUNIVERSITY
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.12,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008,UNIVERSITYOFALABAMAATBIRMINGHAM
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.1912,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589,AMRIDGEUNIVERSITY
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.1593,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331,UNIVERSITYOFALABAMAINHUNTSVILLE
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.0754,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308,ALABAMASTATEUNIVERSITY

In [30]:
# join all-data mod and online_schools_df
combo_school_df = pd.merge(all_data_df, online_schools_df, on="UP_INSTNM", how="left")

combo_school_df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP,UP_INSTNM,Online
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852,ALABAMAAMUNIVERSITY,NaN
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008,UNIVERSITYOFALABAMAATBIRMINGHAM,TRUE
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589,AMRIDGEUNIVERSITY,NaN
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331,UNIVERSITYOFALABAMAINHUNTSVILLE,TRUE
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308,ALABAMASTATEUNIVERSITY,NaN
5,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487-0166,Southern Association of Colleges and Schools C...,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,...,0.0073,0.2431,0.6817,0.0679,0.0142,0.2842,0.4599,0.2416,THEUNIVERSITYOFALABAMA,NaN
6,100760,100700,1007,Central Alabama Community College,Alexander City,AL,35010,Southern Association of Colleges and Schools C...,www.cacc.edu,https://www.cacc.edu/net-price-calculator/,...,0.0142,0.3794,0.2206,0.3858,0.0092,0.3258,0.2769,0.3881,CENTRALALABAMACOMMUNITYCOLLEGE,NaN
7,100812,100800,1008,Athens State University,Athens,AL,35611,Southern Association of Colleges and Schools C...,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,...,0.0109,0.1797,0.649,0.1604,0.0181,0.2112,0.4741,0.2966,ATHENSSTATEUNIVERSITY,NaN
8,100830,831000,8310,Auburn University at Montgomery,Montgomery,AL,36117-3596,Southern Association of Colleges and Schools C...,www.aum.edu,www.aum.edu/current-students/financial-informa...,...,0.0134,0.4208,0.327,0.2388,0.0289,0.3737,0.2352,0.3622,AUBURNUNIVERSITYATMONTGOMERY,NaN
9,100858,100900,1009,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,www.auburn.edu,https://www.auburn.edu/admissions/costcalc/fre...,...,0.0062,0.2026,0.7405,0.0506,0.0143,0.3829,0.4571,0.1457,AUBURNUNIVERSITY,TRUE
10,100937,101200,1012,Birmingham Southern College,Birmingham,AL,35254,Southern Association of Colleges and Schools C...,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,...,0.0031,0.3303,0.6319,0.0348,NaN,NaN,NaN,NaN,BIRMINGHAMSOUTHERNCOLLEGE,NaN
11,101028,1218200,12182,Chattahoochee Valley Community College,Phenix City,AL,36869,Southern Association of Colleges and Schools C...,www.cv.edu,www.cv.edu/about/consumer-information/,...,0.0155,0.5959,0.2216,0.167,0.0067,0.5705,0.1678,0.255,CHATTAHOOCHEEVALLEYCOMMUNITYCOLLEGE,NaN
12,101073,1055400,10554,Concordia College Alabama,Selma,AL,36701,NaN,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,...,0.006,0.2376,0.1037,0.6526,0,0.2075,0.0094,0.783,CONCORDIACOLLEGEALABAMA,NaN
13,101116,1303906,13039,South University-Montgomery,Montgomery,AL,36116,Southern Association of Colleges and Schools C...,www.southuniversity.edu/montgomery#location=Mo...,www.southuniversity.edu/montgomery/net-price-c...,...,0,0.1263,0.2184,0.6553,0.0035,0.0804,0.2308,0.6853,SOUTHUNIVERSITYMONTGOMERY,NaN
14,101143,101500,1015,Enterprise State Community College,Enterprise,AL,36330-1300,Southern Association of Colleges and Schools C...,www.escc.edu,https://www.escc.edu/netprice/npcalc.htm,...,0.0095,0.3663,0.3104,0.3138,0.004,0.4113,0.1707,0.414,ENTERPRISESTATECOMMUNITYCOLLEGE,NaN
15,101161,106000,1060,Coastal Alabama Community College,Bay Minette,AL,36507-2698,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.0119,0.5981,0.2845,0.1056,0.019,0.5704,0.2838,0.1268,COASTALALABAMACOMMUNITYCOLLEGE,NaN
16,101189,100300,1003,Faulkner University,Montgomery,AL,36109-3390,Southern Association of Colleges and Schools C...,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,...,0.0057,0.3406,0.4638,0.19,0.0112,0.3825,0.3582,0.2481,FAULKNERUNIVERSITY,TRUE
17,101240,101700,1017,Gadsden State Community College,Gadsden,AL,35903,Southern Association of Colleges and Schools C...,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,...,0.0215,0.1641,0.2742,0.5402,0.0835,0.1191,0.2338,0.5636,GADSDENSTATECOMMUNITYCOLLEGE,NaN
18,101277,4187200,41872,New Beginning College of Cosmetology,Albertville,AL,35951,National Accrediting Commission of Career Arts...,www.nbccosmetology.com,nbccosmetology.com/sa/nbc_zonemap/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEWBEGINNINGCOLLEGEOFCOSMETOLOGY,NaN
19,101286,101800,1018,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,Southern Association of Colleges and Schools C...,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,...,0.0221,0.2986,0.2993,0.3799,0.043,0.2557,0.2743,0.427,GEORGECWALLACECOMMUNITYCOLLEGEDOTHAN,NaN
20,101295,787100,7871,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,Southern Association of Colleges and Schools C...,www.wallacestate.edu,www.wallacestate.edu/Financial-Aid/Net-Price-C...,...,0.0084,0.2639,0.3458,0.3818,0.0103,0.374,0.2665,0.3492,GEORGECWALLACESTATECOMMUNITYCOLLEGEHANCEVILLE,NaN
21,101301,569900,5699,George C Wallace State Community College-Selma,Selma,AL,36703-2808,Southern Association of Colleges and Schools C...,www.wccs.edu,www.wccs.edu/financial-aid/about-financial-aid/,...,0.1991,0.1513,0.3276,0.3221,0.1536,0.1348,0.2102,0.5013,GEORGECWALLACESTATECOMMUNITYCOLLEGESELMA,NaN
22,101365,962107,9621,Herzing University-Birmingham,Birmingham,AL,35209,Higher Learning Commission,https://www.herzing.edu/,https://www.herzing.edu/tuition-financial-aid/...,...,0,0.1046,0.634,0.2614,0,0.1685,0.3641,0.4674,HERZINGUNIVERSITYBIRMINGHAM,NaN
23,101435,101900,1019,Huntingdon College,Montgomery,AL,36106-2148,Southern Association of Colleges and Schools C...,www.huntingdon.edu,hawk.huntingdon.edu/oiac/netpricecalculator/np...,...,0.0032,0.3946,0.4628,0.1395,0.0036,0.208,0.5985,0.1898,HUNTINGDONCOLLEGE,NaN
24,101453,2199700,21997,Heritage Christian University,Florence,AL,35630-9977,Association for Bibical Higher Educaiton,www.hcu.edu,www.hcu.edu/netpricecalculator/,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,0,0,0.1333,0.8667,HERITAGECHRISTIANUNIVERSITY,NaN
25,101462,526000,5260,J. F. Drake State Community and Technical College,Huntsville,AL,35811,Southern Association of Colleges and Schools C...,www.drakestate.edu,www.drakestate.edu/admissions/net_price_calcul...,...,0.0054,0.3074,0.3243,0.3629,0.0038,0.3094,0.2541,0.4327,JFDRAKESTATECOMMUNITYANDTECHNICALCOLLEGE,NaN
26,101471,3002500,30025,J F Ingram State Technical College,Deatsville,AL,36022,Council on Occupational Education,www.istc.edu,nces.ed.gov/ipeds/netpricecalculator/Npc_2.aspx,...,0.004,0,0.4279,0.5681,0.0097,0,0.2379,0.7524,JFINGRAMSTATETECHNICALCOLLEGE,NaN
27,101480,102000,1020,Jacksonville State University,Jacksonville,AL,36265,Southern Association of Colleges and Schools C...,www.jsu.edu/,www.jsu.edu/finaid/,...,0.0247,0,0.3965,0.5787,0.0219,0,0.48,0.4981,JACKSONVILLESTATEUNIVERSITY,TRUE
28,101499,106010,1060,Jefferson Davis Community College,Brewton,AL,36426,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.031,0.1742,0.3703,0.4245,0.0426,0.1632,0.3386,0.4555,JEFFERSONDAVISCOMMUNITYCOLLEGE,NaN
29,101505,102200,1022,Jefferson State Community College,Birmingham,AL,35215-3098,Southern Association of Colleges and Schools C...,www.jeffersonstate.edu/,www.jeffersonstate.edu/financial-aid/net-price...,...,0.0266,0.4977,0.193,0.2827,0.0191,0.5436,0.1019,0.3354,JEFFERSONSTATECOMMUNITYCOLLEGE,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7028,47503301,4208601,42086,Relay Graduate School of Education - Newark,Newark,NJ,7102,Middle States Commission on Higher Education,relay.edu/location/relay-newark,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNEWARK,NaN
7029,47503302,4208602,42086,Relay Graduate School of Education - New Orleans,New Orleans,LA,70112,Middle States Commission on Higher Education,relay.edu/location/relay-new-orleans,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNEWORLEANS,NaN
7030,47503303,4208605,42086,Relay Graduate School of Education - Delaware,Wilmington,DE,19801,Middle States Commission on Higher Education,relay.edu/location/relay-delaware,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDELAWARE,NaN
7031,47503304,4208606,42086,Relay Graduate School of Education - Memphis,Memphis,TN,38104,Middle States Commission on Higher Education,relay.edu/location/relay-memphis,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONMEMPHIS,NaN
7032,47503305,4208603,42086,Relay Graduate School of Education - Houston,Houston,TX,770744906,Middle States Commission on Higher Education,relay.edu/location/relay-houston,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONHOUSTON,NaN
7033,47503306,4208604,42086,Relay Graduate School of Education - Chicago,Chicago,IL,606324906,Middle States Commission on Higher Education,relay.edu/location/relay-chicago,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONCHICAGO,NaN
7034,47503307,4208607,42086,Relay Graduate School of Education - Baton Rouge,Baton Rouge,LA,708114906,Middle States Commission on Higher Education,relay.edu/location/relay-baton-rouge,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONBATONROUGE,NaN
7035,47503308,4208608,42086,Relay Graduate School of Education - Philadelp...,Philadelphia,PA,191224906,Middle States Commission on Higher Education,relay.edu/location/relay-philadelphia-camden,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONPHILADELPHIACAMDEN,NaN
7036,47503309,4208609,42086,Relay Graduate School of Education - Denver,Denver,CO,802112534,Middle States Commission on Higher Education,relay.edu/location/relay-denver,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDENVER,NaN
7037,47503310,4208610,42086,Relay Graduate School of Education - Nashville,Nashville,TN,372075155,Middle States Commission on Higher Education,relay.edu/location/relay-nashville,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNASHVILLE,NaN
7038,47503311,4208611,42086,Relay Graduate School of Education - San Antonio,San Antonio,TX,782155155,Middle States Commission on Higher Education,relay.edu/location/relay-san-antonio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONSANANTONIO,NaN
7039,47503312,4208612,42086,Relay Graduate School of Education - Dallas-Fo...,Dallas,TX,752075155,Middle States Commission on Higher Education,relay.edu/location/relay-dallas-fort-worth,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDALLASFORTWORTH,NaN
7040,47503313,4208613,42086,Relay Graduate School of Education - Washingto...,Washington,DC,200375155,Middle States Commission on Higher Education,relay.edu/location/relay-washington-dc,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONWASHINGTONDC,NaN
7041,47647001,4088301,40883,WestMed College - Merced,Merced,CA,953400000,NaN,www.westmedcollege.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WESTMEDCOLLEGEMERCED,NaN
7042,47662901,4189101,41891,Salon Institute - Columbus Campus,Lewis Center,OH,430359153,National Accrediting Commission of Career Arts...,www.saloninstitute.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SALONINSTITUTECOLUMBUSCAMPUS,NaN
7043,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,94608,NaN,usa.sae.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SAEINSTITUTEOFTECHNOLOGYSANFRANCISCO,NaN
7044,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,662102786,Higher Learning Commission,rasmussen.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RASMUSSENCOLLEGEOVERLANDPARK,NaN
7045,48079001,4218901,42189,Rocky Vista University - Southern Utah,Ivins,UT,847386756,Higher Learning Commission,www.rvu.edu/rvu-su/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ROCKYVISTAUNIVERSITYSOUTHERNUTAH,NaN
7046,48092101,4220001,42200,Designer Barber & Stylist School -,Springdale,AR,727620990,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESIGNERBARBERSTYLISTSCHOOL,NaN
7047,48133101,4213501,42135,Sharp Edgez Barber Institute - Buffalo,Buffalo,NY,142170000,Council on Occupational Education,www.sharpedgezbarberinstitute.com,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SHARPEDGEZBARBERINSTITUTEBUFFALO,NaN
7048,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,44143,Accrediting Council for Continuing Education &...,nptiohio.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NATIONALPERSONALTRAININGINSTITUTEOFCLEVELAND,NaN
7049,48305401,4224601,42246,Barber School of Pittsburgh - Ambridge,Ambridge,PA,150030000,NaN,www.bsp.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BARBERSCHOOLOFPITTSBURGHAMBRIDGE,NaN
7050,48312401,108131,1081,Arizona State University at Tucson,Tucson,AZ,857454284,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATTUCSON,NaN
7051,48312402,108161,1081,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,864036877,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYASUCOLLEGESATLAKEHAVASUCITY,NaN
7052,48312403,108162,1081,Arizona State University at The Gila Valley,Thatcher,AZ,855525545,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATTHEGILAVALLEY,NaN
7053,48312404,108163,1081,Arizona State University at Yuma,Yuma,AZ,853656900,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATYUMA,NaN
7054,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,Accrediting Council for Independent Colleges a...,www.bamasf.com/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BAYAREAMEDICALACADEMYSANJOSESATELLITELOCATION,NaN
7055,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,935340000,Accrediting Council for Continuing Education &...,www.hdmc.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HIGHDESERTMEDICALCOLLEGE,NaN
7056,48778201,4221501,42215,BCI - Malden,Malden,MA,21480000,NaN,bostoncareer.org,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BCIMALDEN,NaN
7057,49005401,4182601,41826,Health Career Institute- Lauderdale Lakes,Lauderdale Lakes,FL,333137268,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HEALTHCAREERINSTITUTELAUDERDALELAKES,NaN

In [40]:
UPINSTN=[]
for index,row in combo_school_df.iterrows():
    if row["Online"]=="TRUE":
        UPINSTN.append(row["UP_INSTNM"])
        print(row["UP_INSTNM"])

UNIVERSITYOFALABAMAATBIRMINGHAM
UNIVERSITYOFALABAMAINHUNTSVILLE
AUBURNUNIVERSITY
FAULKNERUNIVERSITY
JACKSONVILLESTATEUNIVERSITY
JUDSONCOLLEGE
UNIVERSITYOFWESTALABAMA
UNIVERSITYOFNORTHALABAMA
SAMFORDUNIVERSITY
UNIVERSITYOFSOUTHALABAMA
TROYUNIVERSITY
UNIVERSITYOFALASKAFAIRBANKS
UNIVERSITYOFARIZONA
GRANDCANYONUNIVERSITY
NORTHERNARIZONAUNIVERSITY
PRESCOTTCOLLEGE
UNIVERSITYOFARKANSAS
UNIVERSITYOFCENTRALARKANSAS
JOHNBROWNUNIVERSITY
BIOLAUNIVERSITY
CALIFORNIABAPTISTUNIVERSITY
CALIFORNIASTATEUNIVERSITYSANBERNARDINO
CALIFORNIASTATEUNIVERSITYFULLERTON
CALIFORNIASTATEUNIVERSITYNORTHRIDGE
UNIVERSITYOFCALIFORNIABERKELEY
UNIVERSITYOFCALIFORNIAIRVINE
UNIVERSITYOFCALIFORNIALOSANGELES
CONCORDIAUNIVERSITYIRVINE
CLAREMONTGRADUATEUNIVERSITY
UNIVERSITYOFLAVERNE
HOPEINTERNATIONALUNIVERSITY
PACIFICOAKSCOLLEGE
PEPPERDINEUNIVERSITY
UNIVERSITYOFREDLANDS
UNIVERSITYOFSOUTHERNCALIFORNIA
WALDENUNIVERSITY
ADAMSSTATEUNIVERSITY
UNIVERSITYOFCOLORADOCOLORADOSPRINGS
UNIVERSITYOFCOLORADOBOULDER
COLORADOCHRISTIANUNIVERSITY
COLORADOSTATEUNIVERSITYFORTCOLLINS
UNIVERSITYOFDENVER
COLORADOMESAUNIVERSITY
METROPOLITANSTATEUNIVERSITYOFDENVER
UNIVERSITYOFNORTHERNCOLORADO
REGISUNIVERSITY
COLORADOSTATEUNIVERSITYPUEBLO
UNIVERSITYOFBRIDGEPORT
UNIVERSITYOFHARTFORD
UNIVERSITYOFNEWHAVEN
QUINNIPIACUNIVERSITY
SACREDHEARTUNIVERSITY
UNIVERSITYOFDELAWARE
AMERICANUNIVERSITY
GEORGETOWNUNIVERSITY
THEBAPTISTCOLLEGEOFFLORIDA
BARRYUNIVERSITY
LYNNUNIVERSITY
UNIVERSITYOFCENTRALFLORIDA
FLORIDAATLANTICUNIVERSITY
FLORIDASTATECOLLEGEATJACKSONVILLE
FLORIDAINTERNATIONALUNIVERSITY
FLORIDASTATEUNIVERSITY
UNIVERSITYOFFLORIDA
FULLSAILUNIVERSITY
JACKSONVILLEUNIVERSITY
NOVASOUTHEASTERNUNIVERSITY
UNIVERSITYOFSOUTHFLORIDAMAINCAMPUS
SOUTHEASTERNUNIVERSITY
WARNERUNIVERSITY
THEUNIVERSITYOFWESTFLORIDA
BRENAUUNIVERSITY
COLUMBUSSTATEUNIVERSITY
EMORYUNIVERSITY
FORTVALLEYSTATEUNIVERSITY
GEORGIASOUTHWESTERNSTATEUNIVERSITY
GEORGIACOLLEGESTATEUNIVERSITY
GEORGIASOUTHERNUNIVERSITY
GEORGIASTATEUNIVERSITY
UNIVERSITYOFGEORGIA
MERCERUNIVERSITY
SAVANNAHCOLLEGEOFARTANDDESIGN
SHORTERUNIVERSITY
TOCCOAFALLSCOLLEGE
TRUETTMCCONNELLUNIVERSITY
VALDOSTASTATEUNIVERSITY
CHAMINADEUNIVERSITYOFHONOLULU
BOISESTATEUNIVERSITY
UNIVERSITYOFIDAHO
LEWISCLARKSTATECOLLEGE
NORTHWESTNAZARENEUNIVERSITY
BRADLEYUNIVERSITY
DEPAULUNIVERSITY
EASTERNILLINOISUNIVERSITY
ELMHURSTCOLLEGE
BENEDICTINEUNIVERSITY
ILLINOISINSTITUTEOFTECHNOLOGY
JUDSONUNIVERSITY
LEWISUNIVERSITY
LOYOLAUNIVERSITYCHICAGO
MCKENDREEUNIVERSITY
NATIONALLOUISUNIVERSITY
NORTHERNILLINOISUNIVERSITY
NORTHWESTERNUNIVERSITY
OLIVETNAZARENEUNIVERSITY
ROOSEVELTUNIVERSITY
DOMINICANUNIVERSITY
UNIVERSITYOFSTFRANCIS
SAINTXAVIERUNIVERSITY
UNIVERSITYOFILLINOISATSPRINGFIELD
SOUTHERNILLINOISUNIVERSITYCARBONDALE
WESTERNILLINOISUNIVERSITY
BALLSTATEUNIVERSITY
GRACECOLLEGEANDTHEOLOGICALSEMINARY
HUNTINGTONUNIVERSITY
INDIANAINSTITUTEOFTECHNOLOGY
UNIVERSITYOFSOUTHERNINDIANA
INDIANASTATEUNIVERSITY
INDIANAUNIVERSITYBLOOMINGTON
INDIANAUNIVERSITYNORTHWEST
INDIANAUNIVERSITYEAST
UNIVERSITYOFNOTREDAME
OAKLANDCITYUNIVERSITY
SAINTMARYOFTHEWOODSCOLLEGE
VALPARAISOUNIVERSITY
BUENAVISTAUNIVERSITY
IOWACENTRALCOMMUNITYCOLLEGE
IOWASTATEUNIVERSITY
UNIVERSITYOFIOWA
MORNINGSIDECOLLEGE
MOUNTMERCYUNIVERSITY
ASHFORDUNIVERSITY
UNIVERSITYOFNORTHERNIOWA
UPPERIOWAUNIVERSITY
WALDORFUNIVERSITY
CENTRALCHRISTIANCOLLEGEOFKANSAS
EMPORIASTATEUNIVERSITY
FRIENDSUNIVERSITY
KANSASCHRISTIANCOLLEGE
UNIVERSITYOFKANSAS
NEWMANUNIVERSITY
UNIVERSITYOFSAINTMARY
TABORCOLLEGE
WICHITASTATEUNIVERSITY
BRESCIAUNIVERSITY
CAMPBELLSVILLEUNIVERSITY
UNIVERSITYOFTHECUMBERLANDS
EASTERNKENTUCKYUNIVERSITY
GEORGETOWNCOLLEGE
KENTUCKYSTATEUNIVERSITY
KENTUCKYWESLEYANCOLLEGE
UNIVERSITYOFKENTUCKY
UNIVERSITYOFLOUISVILLE
MOREHEADSTATEUNIVERSITY
MURRAYSTATEUNIVERSITY
NORTHERNKENTUCKYUNIVERSITY
THESOUTHERNBAPTISTTHEOLOGICALSEMINARY
THOMASMORECOLLEGE
WESTERNKENTUCKYUNIVERSITY
LOUISIANASTATEUNIVERSITYALEXANDRIA
LOUISIANASTATEUNIVERSITYSHREVEPORT
LOUISIANATECHUNIVERSITY
LOYOLAUNIVERSITYNEWORLEANS
MCNEESESTATEUNIVERSITY
NICHOLLSSTATEUNIVERSITY
NORTHWESTERNSTATEUNIVERSITYOFLOUISIANA
FRANCISCANMISSIONARIESOFOURLADYUNIVERSITY
SOUTHERNUNIVERSITYANDAMCOLLEGE
UNIVERSITYOFMAINEATFORTKENT
UNIVERSITYOFMAINE
UNIVERSITYOFSOUTHERNMAINE
CAPITOLTECHNOLOGYUNIVERSITY
FROSTBURGSTATEUNIVERSITY
JOHNSHOPKINSUNIVERSITY
UNIVERSITYOFMARYLANDUNIVERSITYCOLLEGE
UNIVERSITYOFMARYLANDCOLLEGEPARK
NOTREDAMEOFMARYLANDUNIVERSITY
TOWSONUNIVERSITY
STEVENSONUNIVERSITY
AMERICANINTERNATIONALCOLLEGE
ANNAMARIACOLLEGE
BOSTONUNIVERSITY
BRANDEISUNIVERSITY
FITCHBURGSTATEUNIVERSITY
FRAMINGHAMSTATEUNIVERSITY
LESLEYUNIVERSITY
UNIVERSITYOFMASSACHUSETTSLOWELL
UNIVERSITYOFMASSACHUSETTSAMHERST
UNIVERSITYOFMASSACHUSETTSBOSTON
NORTHEASTERNUNIVERSITY
REGISCOLLEGE
UNIVERSITYOFMASSACHUSETTSDARTMOUTH
WESTERNNEWENGLANDUNIVERSITY
CENTRALMICHIGANUNIVERSITY
DAVENPORTUNIVERSITY
UNIVERSITYOFDETROITMERCY
EASTERNMICHIGANUNIVERSITY
FERRISSTATEUNIVERSITY
ROCHESTERCOLLEGE
UNIVERSITYOFMICHIGANANNARBOR
MICHIGANSTATEUNIVERSITY
UNIVERSITYOFMICHIGANDEARBORN
UNIVERSITYOFMICHIGANFLINT
NORTHERNMICHIGANUNIVERSITY
SIENAHEIGHTSUNIVERSITY
WAYNESTATEUNIVERSITY
WESTERNMICHIGANUNIVERSITY
HAMLINEUNIVERSITY
HAZELDENBETTYFORDGRADUATESCHOOLOFADDICTIONSTUDIES
UNIVERSITYOFMINNESOTATWINCITIES
UNIVERSITYOFMINNESOTACROOKSTON
MINNESOTASTATEUNIVERSITYMOORHEAD
NORTHCENTRALUNIVERSITY
UNIVERSITYOFNORTHWESTERNSTPAUL
SAINTCLOUDSTATEUNIVERSITY
SAINTMARY'SUNIVERSITYOFMINNESOTA
CROWNCOLLEGE
THECOLLEGEOFSAINTSCHOLASTICA
STCATHERINEUNIVERSITY
DELTASTATEUNIVERSITY
JACKSONSTATEUNIVERSITY
MISSISSIPPICOLLEGE
MISSISSIPPISTATEUNIVERSITY
UNIVERSITYOFSOUTHERNMISSISSIPPI
WILLIAMCAREYUNIVERSITY
CALVARYUNIVERSITY
UNIVERSITYOFCENTRALMISSOURI
CULVERSTOCKTONCOLLEGE
DRURYUNIVERSITY
EVANGELUNIVERSITY
FONTBONNEUNIVERSITY
LINDENWOODUNIVERSITY
MIDWESTERNBAPTISTTHEOLOGICALSEMINARY
MISSOURIBAPTISTUNIVERSITY
MISSOURISOUTHERNSTATEUNIVERSITY
UNIVERSITYOFMISSOURIKANSASCITY
MISSOURIUNIVERSITYOFSCIENCEANDTECHNOLOGY
NORTHWESTMISSOURISTATEUNIVERSITY
ROCKHURSTUNIVERSITY
STEPHENSCOLLEGE
SOUTHEASTMISSOURISTATEUNIVERSITY
WEBSTERUNIVERSITY
WILLIAMWOODSUNIVERSITY
MONTANASTATEUNIVERSITY
THEUNIVERSITYOFMONTANA
MONTANASTATEUNIVERSITYNORTHERN
BELLEVUEUNIVERSITY
CONCORDIAUNIVERSITYNEBRASKA
CREIGHTONUNIVERSITY
UNIVERSITYOFNEBRASKAATKEARNEY
UNIVERSITYOFNEBRASKAATOMAHA
UNIVERSITYOFNEBRASKALINCOLN
YORKCOLLEGE
UNIVERSITYOFNEVADARENO
NEWENGLANDCOLLEGE
FAIRLEIGHDICKINSONUNIVERSITYMETROPOLITANCAMPUS
ROWANUNIVERSITY
NEWJERSEYINSTITUTEOFTECHNOLOGY
SETONHALLUNIVERSITY
COLLEGEOFSAINTELIZABETH
THOMASEDISONSTATEUNIVERSITY
EASTERNNEWMEXICOUNIVERSITYMAINCAMPUS
UNIVERSITYOFTHESOUTHWEST
ADELPHIUNIVERSITY
CANISIUSCOLLEGE
CLARKSONUNIVERSITY
COLUMBIAUNIVERSITYINTHECITYOFNEWYORK
CONCORDIACOLLEGENEWYORK
CUNYJOHNJAYCOLLEGEOFCRIMINALJUSTICE
MANHATTANCOLLEGE
NEWYORKUNIVERSITY
NYACKCOLLEGE
ROCHESTERINSTITUTEOFTECHNOLOGY
UNIVERSITYATBUFFALO
SYRACUSEUNIVERSITY
EXCELSIORCOLLEGE
UTICACOLLEGE
APPALACHIANSTATEUNIVERSITY
DUKEUNIVERSITY
EASTCAROLINAUNIVERSITY
FAYETTEVILLESTATEUNIVERSITY
GARDNERWEBBUNIVERSITY
UNIVERSITYOFMOUNTOLIVE
NORTHCAROLINAATSTATEUNIVERSITY
UNIVERSITYOFNORTHCAROLINAATCHAPELHILL
UNIVERSITYOFNORTHCAROLINAATCHARLOTTE
UNIVERSITYOFNORTHCAROLINAATGREENSBORO
NORTHCAROLINACENTRALUNIVERSITY
UNIVERSITYOFNORTHCAROLINAATPEMBROKE
PFEIFFERUNIVERSITY
QUEENSUNIVERSITYOFCHARLOTTE
WESTERNCAROLINAUNIVERSITY
DICKINSONSTATEUNIVERSITY
UNIVERSITYOFMARY
MINOTSTATEUNIVERSITY
UNIVERSITYOFNORTHDAKOTA
NORTHDAKOTASTATEUNIVERSITYMAINCAMPUS
VALLEYCITYSTATEUNIVERSITY
BOWLINGGREENSTATEUNIVERSITYMAINCAMPUS
CINCINNATISTATETECHNICALANDCOMMUNITYCOLLEGE
OHIOCHRISTIANUNIVERSITY
CLEVELANDSTATEUNIVERSITY
UNIVERSITYOFDAYTON
KENTSTATEUNIVERSITYATKENT
MALONEUNIVERSITY
MOUNTVERNONNAZARENEUNIVERSITY
UNIVERSITYOFNORTHWESTERNOHIO
OHIOSTATEUNIVERSITYMAINCAMPUS
OHIOUNIVERSITYMAINCAMPUS
FRANCISCANUNIVERSITYOFSTEUBENVILLE
UNIVERSITYOFTOLEDO
WALSHUNIVERSITY
WRIGHTSTATEUNIVERSITYMAINCAMPUS
YOUNGSTOWNSTATEUNIVERSITY
OKLAHOMAWESLEYANUNIVERSITY
NORTHEASTERNSTATEUNIVERSITY
OKLAHOMACHRISTIANUNIVERSITY
OKLAHOMASTATEUNIVERSITYMAINCAMPUS
UNIVERSITYOFOKLAHOMANORMANCAMPUS
ORALROBERTSUNIVERSITY
ROGERSSTATEUNIVERSITY
SOUTHEASTERNOKLAHOMASTATEUNIVERSITY
SOUTHWESTERNCHRISTIANUNIVERSITY
SOUTHWESTERNOKLAHOMASTATEUNIVERSITY
CONCORDIAUNIVERSITYPORTLAND
EASTERNOREGONUNIVERSITY
OREGONINSTITUTEOFTECHNOLOGY
OREGONSTATEUNIVERSITY
PORTLANDSTATEUNIVERSITY
SOUTHERNOREGONUNIVERSITY
CORBANUNIVERSITY
DESALESUNIVERSITY
ALVERNIAUNIVERSITY
ARCADIAUNIVERSITY
CALIFORNIAUNIVERSITYOFPENNSYLVANIA
CARLOWUNIVERSITY
CARNEGIEMELLONUNIVERSITY
DREXELUNIVERSITY
DUQUESNEUNIVERSITY
EASTERNUNIVERSITY
EDINBOROUNIVERSITYOFPENNSYLVANIA
GANNONUNIVERSITY
IMMACULATAUNIVERSITY
LEHIGHUNIVERSITY
MESSIAHCOLLEGE
MISERICORDIAUNIVERSITY
MOUNTALOYSIUSCOLLEGE
UNIVERSITYOFPITTSBURGHPITTSBURGHCAMPUS
POINTPARKUNIVERSITY
SAINTFRANCISUNIVERSITY
SAINTJOSEPH'SUNIVERSITY
UNIVERSITYOFVALLEYFORGE
VILLANOVAUNIVERSITY

WIDENERUNIVERSITY
WILKESUNIVERSITY
CHARLESTONSOUTHERNUNIVERSITY
CLEMSONUNIVERSITY
COLUMBIAINTERNATIONALUNIVERSITY
NORTHGREENVILLEUNIVERSITY
UNIVERSITYOFSOUTHCAROLINAAIKEN
UNIVERSITYOFSOUTHCAROLINACOLUMBIA
WINTHROPUNIVERSITY
DAKOTASTATEUNIVERSITY
NORTHERNSTATEUNIVERSITY
SOUTHDAKOTASTATEUNIVERSITY
UNIVERSITYOFSIOUXFALLS
UNIVERSITYOFSOUTHDAKOTA
AUSTINPEAYSTATEUNIVERSITY
BRYANCOLLEGEDAYTON
CARSONNEWMANUNIVERSITY
JOHNSONUNIVERSITY
KINGUNIVERSITY
SOUTHCOLLEGE
LEEUNIVERSITY
UNIVERSITYOFMEMPHIS
MIDDLETENNESSEESTATEUNIVERSITY
THEUNIVERSITYOFTENNESSEEKNOXVILLE
THEUNIVERSITYOFTENNESSEEMARTIN
TREVECCANAZARENEUNIVERSITY
UNIONUNIVERSITY
ABILENECHRISTIANUNIVERSITY
ANGELOSTATEUNIVERSITY
BAYLORUNIVERSITY
CONCORDIAUNIVERSITYTEXAS
TEXASAMUNIVERSITYCORPUSCHRISTI
DALLASBAPTISTUNIVERSITY
UNIVERSITYOFDALLAS
TEXASAMUNIVERSITYCOMMERCE
UNIVERSITYOFHOUSTONCLEARLAKE
UNIVERSITYOFHOUSTONDOWNTOWN
UNIVERSITYOFHOUSTON
UNIVERSITYOFTHEINCARNATEWORD
LAMARUNIVERSITY
LETOURNEAUUNIVERSITY
LUBBOCKCHRISTIANUNIVERSITY
MIDWESTERNSTATEUNIVERSITY
UNIVERSITYOFNORTHTEXAS
OURLADYOFTHELAKEUNIVERSITY
SAMHOUSTONSTATEUNIVERSITY
SOUTHERNMETHODISTUNIVERSITY
SOUTHWESTERNASSEMBLIESOFGODUNIVERSITY
STEPHENFAUSTINSTATEUNIVERSITY
TARLETONSTATEUNIVERSITY
TEXASAMUNIVERSITYKINGSVILLE
TEXASAMUNIVERSITYCOLLEGESTATION
THEUNIVERSITYOFTEXASATARLINGTON
THEUNIVERSITYOFTEXASATAUSTIN
THEUNIVERSITYOFTEXASATDALLAS
THEUNIVERSITYOFTEXASATELPASO
THEUNIVERSITYOFTEXASATTYLER
THEUNIVERSITYOFTEXASOFTHEPERMIANBASIN
TEXASTECHUNIVERSITY
TEXASWOMAN'SUNIVERSITY
WAYLANDBAPTISTUNIVERSITY
WESTTEXASAMUNIVERSITY
SOUTHERNUTAHUNIVERSITY
UTAHSTATEUNIVERSITY
UNIVERSITYOFUTAH
CHAMPLAINCOLLEGE
NORWICHUNIVERSITY
BLUEFIELDCOLLEGE
GEORGEMASONUNIVERSITY
HAMPTONUNIVERSITY
JAMESMADISONUNIVERSITY
LIBERTYUNIVERSITY
AMERICANNATIONALUNIVERSITY
OLDDOMINIONUNIVERSITY
VIRGINIAPOLYTECHNICINSTITUTEANDSTATEUNIVERSITY
CENTRALWASHINGTONUNIVERSITY
CITYUNIVERSITYOFSEATTLE
GONZAGAUNIVERSITY
NORTHWESTUNIVERSITY
WASHINGTONSTATEUNIVERSITY
WESTERNWASHINGTONUNIVERSITY
UNIVERSITYOFCHARLESTON
MARSHALLUNIVERSITY
SALEMUNIVERSITY
WESTVIRGINIAUNIVERSITY
WHEELINGJESUITUNIVERSITY
CONCORDIAUNIVERSITYWISCONSIN
LAKELANDUNIVERSITY
VITERBOUNIVERSITY
UNIVERSITYOFWISCONSINWHITEWATER
UNIVERSITYOFWISCONSINLACROSSE
UNIVERSITYOFWISCONSINOSHKOSH
UNIVERSITYOFWISCONSINMADISON
UNIVERSITYOFWISCONSINMILWAUKEE
UNIVERSITYOFWISCONSINPLATTEVILLE
UNIVERSITYOFWISCONSINSTEVENSPOINT
UNIVERSITYOFWYOMING
UNIVERSITYOFTHEVIRGINISLANDS
STANFORDUNIVERSITY
PURDUEUNIVERSITYMAINCAMPUS
CAPELLAUNIVERSITY
WESTERNGOVERNORSUNIVERSITY
FLORIDAGULFCOASTUNIVERSITY
STRATFORDUNIVERSITY
GRANTHAMUNIVERSITY
NORTHCENTRALUNIVERSITY
AMERICANINTERCONTINENTALUNIVERSITY
AMERICANPUBLICUNIVERSITYSYSTEM
COLUMBIASOUTHERNUNIVERSITY
TRIDENTUNIVERSITYINTERNATIONAL
OTTAWAUNIVERSITYONLINE
TOUROUNIVERSITYWORLDWIDE
JOHNSONWALESUNIVERSITYONLINE
INDEPENDENCEUNIVERSITY
COLORADOSTATEUNIVERSITYGLOBALCAMPUS
PENNSYLVANIASTATEUNIVERSITYWORLDCAMPUS
BRYANTSTRATTONCOLLEGEONLINE
SHILOHUNIVERSITY
KENNESAWSTATEUNIVERSITY
CALIFORNIAINSTITUTEOFADVANCEDMANAGEMENT
ABRAHAMLINCOLNUNIVERSITY
PURDUEUNIVERSITYNORTHWEST
UNIVERSITYOFNOTREDAME

In [41]:
#determine how many schools made to list
len(UPINSTN)

476