In [3]:
import pandas as pd
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect
from config import password
import pandas as pd

### Webscraping Credited Online Schools

In [4]:
url = 'https://www.guidetoonlineschools.com/online-schools?f_show=all'

In [5]:
tables = pd.read_html(url)
tables
upper_df=pd.Series

In [6]:
len(tables)

11

In [7]:
type(tables)

list

In [8]:
df = tables[4]
#df.columns = ['School', 'Annual Tuition', 'Recommend Rate']
df.head()

                         School Annual Tuition    Recommend Rate
0  Abilene Christian University        $33,330  100% (6 reviews)
1    Abraham Lincoln University         $7,500  100% (2 reviews)
2        Adams State University        $20,456   50% (2 reviews)
3            Adelphi University        $37,170        Add Review
4           Alvernia University        $33,640        Add Review

In [9]:
strip_df = df.columns
strip2_df= df[strip_df].replace({' ':''}, regex = True)
strip2_df.head()

                       School Annual Tuition  Recommend Rate
0  AbileneChristianUniversity        $33,330  100%(6reviews)
1    AbrahamLincolnUniversity         $7,500  100%(2reviews)
2        AdamsStateUniversity        $20,456   50%(2reviews)
3           AdelphiUniversity        $37,170       AddReview
4          AlverniaUniversity        $33,640       AddReview

In [10]:
strip2_df["School"]=strip2_df["School"].apply(str.upper)
strip2_df.head()

                       School Annual Tuition  Recommend Rate
0  ABILENECHRISTIANUNIVERSITY        $33,330  100%(6reviews)
1    ABRAHAMLINCOLNUNIVERSITY         $7,500  100%(2reviews)
2        ADAMSSTATEUNIVERSITY        $20,456   50%(2reviews)
3           ADELPHIUNIVERSITY        $37,170       AddReview
4          ALVERNIAUNIVERSITY        $33,640       AddReview

In [11]:
online_schools_df = strip2_df.drop(columns =["Annual Tuition", "Recommend Rate"])
online_schools_df.head()

                       School
0  ABILENECHRISTIANUNIVERSITY
1    ABRAHAMLINCOLNUNIVERSITY
2        ADAMSSTATEUNIVERSITY
3           ADELPHIUNIVERSITY
4          ALVERNIAUNIVERSITY

In [12]:
online_schools_df['School'] =online_schools_df['School'].str.replace("&","")
online_schools_df['School'] =online_schools_df['School'].str.replace("-","")
online_schools_df['School'] =online_schools_df['School'].str.replace(".","")

In [13]:
online_schools_df['Online'] = True
online_schools_df.head()

                       School  Online
0  ABILENECHRISTIANUNIVERSITY    True
1    ABRAHAMLINCOLNUNIVERSITY    True
2        ADAMSSTATEUNIVERSITY    True
3           ADELPHIUNIVERSITY    True
4          ALVERNIAUNIVERSITY    True

In [14]:
online_schools_df = online_schools_df.rename(columns={"School":"UP_INSTNM"})
online_schools_df.head()

                    UP_INSTNM  Online
0  ABILENECHRISTIANUNIVERSITY    True
1    ABRAHAMLINCOLNUNIVERSITY    True
2        ADAMSSTATEUNIVERSITY    True
3           ADELPHIUNIVERSITY    True
4          ALVERNIAUNIVERSITY    True

In [15]:
online_schools_df.set_index("UP_INSTNM")

                                                Online
UP_INSTNM
ABILENECHRISTIANUNIVERSITY                        True
ABRAHAMLINCOLNUNIVERSITY                          True
ADAMSSTATEUNIVERSITY                              True
ADELPHIUNIVERSITY                                 True
ALVERNIAUNIVERSITY                                True
AMERICANINTERCONTINENTALUNIVERSITY                True
AMERICANINTERNATIONALCOLLEGE                      True
AMERICANNATIONALUNIVERSITY                        True
AMERICANPUBLICUNIVERSITYSYSTEM                    True
AMERICANUNIVERSITY                                True
AMERICANUNIVERSITYMBA                             True
ANDERSONUNIVERSITYSC                              True
ANGELOSTATEUNIVERSITY                             True
ANNAMARIACOLLEGE                                  True
ANTIOCHUNIVERSITYONLINE                           True
APPALACHIANSTATEUNIVERSITY                        True
ARCADIAUNIVERSITY                                 True
ARIZONASTATEUNIVERSITY                            True
ARKANSASSTATEUNIVERSITY                           True
ASHFORDUNIVERSITY                                 True
AUBURNUNIVERSITY                                  True
AUGUSTANAUNIVERSITYSD                             True
AUSTINPEAYSTATEUNIVERSITY                         True
BAKERCOLLEGEONLINE                                True
BALLSTATEUNIVERSITY                               True
THEBAPTISTCOLLEGEOFFLORIDA                        True
BARRYUNIVERSITY                                   True
BAYLORUNIVERSITY                                  True
BELLEVUEUNIVERSITY                                True
BENEDICTINEUNIVERSITY                             True
...                                                ...
VIRGINIAPOLYTECHNICINSTITUTEANDSTATEUNIVERSITY    True
VITERBOUNIVERSITY                                 True
WALDENUNIVERSITY                                  True
WALDORFUNIVERSITY                                 True
WALSHUNIVERSITY                                   True
WARNERUNIVERSITY                                  True
WASHINGTONSTATEUNIVERSITY                         True
WAYLANDBAPTISTUNIVERSITY                          True
WAYNESTATEUNIVERSITY                              True
WEBSTERUNIVERSITY                                 True
WESTCOASTUNIVERSITY                               True
WESTTEXASAMUNIVERSITY                             True
WESTVIRGINIAUNIVERSITY                            True
WESTERNCAROLINAUNIVERSITY                         True
WESTERNGOVERNORSUNIVERSITY                        True
WESTERNILLINOISUNIVERSITY                         True
WESTERNKENTUCKYUNIVERSITY                         True
WESTERNMICHIGANUNIVERSITY                         True
WESTERNNEWENGLANDUNIVERSITY                       True
WESTERNWASHINGTONUNIVERSITY                       True
WHEELINGJESUITUNIVERSITY                          True
WICHITASTATEUNIVERSITY                            True
WIDENERUNIVERSITY                                 True
WILKESUNIVERSITY                                  True
WILLIAMCAREYUNIVERSITY                            True
WILLIAMWOODSUNIVERSITY                            True
WINTHROPUNIVERSITY                                True
WRIGHTSTATEUNIVERSITYMAINCAMPUS                   True
YORKCOLLEGE                                       True
YOUNGSTOWNSTATEUNIVERSITY                         True

[567 rows x 1 columns]

In [16]:
online_schools_df.to_csv('Resources/Online-schools.csv')

In [17]:
print(online_schools_df)

                                          UP_INSTNM  Online
0                        ABILENECHRISTIANUNIVERSITY    True
1                          ABRAHAMLINCOLNUNIVERSITY    True
2                              ADAMSSTATEUNIVERSITY    True
3                                 ADELPHIUNIVERSITY    True
4                                ALVERNIAUNIVERSITY    True
5                AMERICANINTERCONTINENTALUNIVERSITY    True
6                      AMERICANINTERNATIONALCOLLEGE    True
7                        AMERICANNATIONALUNIVERSITY    True
8                    AMERICANPUBLICUNIVERSITYSYSTEM    True
9                                AMERICANUNIVERSITY    True
10                            AMERICANUNIVERSITYMBA    True
11                             ANDERSONUNIVERSITYSC    True
12                            ANGELOSTATEUNIVERSITY    True
13                                 ANNAMARIACOLLEGE    True
14                          ANTIOCHUNIVERSITYONLINE    True
15                       APPALACHIANSTATEUNIVERSITY    True
16                                ARCADIAUNIVERSITY    True
17                           ARIZONASTATEUNIVERSITY    True
18                          ARKANSASSTATEUNIVERSITY    True
19                                ASHFORDUNIVERSITY    True
20                                 AUBURNUNIVERSITY    True
21                            AUGUSTANAUNIVERSITYSD    True
22                        AUSTINPEAYSTATEUNIVERSITY    True
23                               BAKERCOLLEGEONLINE    True
24                              BALLSTATEUNIVERSITY    True
25                       THEBAPTISTCOLLEGEOFFLORIDA    True
26                                  BARRYUNIVERSITY    True
27                                 BAYLORUNIVERSITY    True
28                               BELLEVUEUNIVERSITY    True
29                            BENEDICTINEUNIVERSITY    True
..                                              ...     ...
537  VIRGINIAPOLYTECHNICINSTITUTEANDSTATEUNIVERSITY    True
538                               VITERBOUNIVERSITY    True
539                                WALDENUNIVERSITY    True
540                               WALDORFUNIVERSITY    True
541                                 WALSHUNIVERSITY    True
542                                WARNERUNIVERSITY    True
543                       WASHINGTONSTATEUNIVERSITY    True
544                        WAYLANDBAPTISTUNIVERSITY    True
545                            WAYNESTATEUNIVERSITY    True
546                               WEBSTERUNIVERSITY    True
547                             WESTCOASTUNIVERSITY    True
548                           WESTTEXASAMUNIVERSITY    True
549                          WESTVIRGINIAUNIVERSITY    True
550                       WESTERNCAROLINAUNIVERSITY    True
551                      WESTERNGOVERNORSUNIVERSITY    True
552                       WESTERNILLINOISUNIVERSITY    True
553                       WESTERNKENTUCKYUNIVERSITY    True
554                       WESTERNMICHIGANUNIVERSITY    True
555                     WESTERNNEWENGLANDUNIVERSITY    True
556                     WESTERNWASHINGTONUNIVERSITY    True
557                        WHEELINGJESUITUNIVERSITY    True
558                          WICHITASTATEUNIVERSITY    True
559                               WIDENERUNIVERSITY    True
560                                WILKESUNIVERSITY    True
561                          WILLIAMCAREYUNIVERSITY    True
562                          WILLIAMWOODSUNIVERSITY    True
563                              WINTHROPUNIVERSITY    True
564                 WRIGHTSTATEUNIVERSITYMAINCAMPUS    True
565                                     YORKCOLLEGE    True
566                       YOUNGSTOWNSTATEUNIVERSITY    True

[567 rows x 2 columns]

In [18]:
online_schools_df.count()

UP_INSTNM    567
Online       567
dtype: int64

### Joining Online Accredited School with All-Data

In [19]:
all_data = "Resources/All_Data.csv"
all_data_df = pd.read_csv(all_data)

C:\Users\yujin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (6,9,31,1608,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1688,1689,1690,1691,1692,1703,1704,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824,1830,1831,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1909,1910,1911,1912,1913,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [20]:
#Add column of institution name (Strings only)
all_data_df['UP_INSTNM'] = all_data_df['INSTNM']

In [21]:
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.upper() 
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace(" ","")
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace("-","")
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace("&","")
all_data_df['UP_INSTNM'] = all_data_df['UP_INSTNM'].str.replace(".","")
all_data_df.head()
# print(all_data_df['UP_INSTNM'])

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP,UP_INSTNM
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.2645,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852,ALABAMAAMUNIVERSITY
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.12,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008,UNIVERSITYOFALABAMAATBIRMINGHAM
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.1912,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589,AMRIDGEUNIVERSITY
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.1593,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331,UNIVERSITYOFALABAMAINHUNTSVILLE
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.0754,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308,ALABAMASTATEUNIVERSITY

In [24]:
# join all-data mod and online_schools_df
combo_school_df = pd.merge(all_data_df, online_schools_df, on="UP_INSTNM", how="left")
combo_school_df = combo_school_df.fillna(value={'Online':False})
combo_school_df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP,UP_INSTNM,Online
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852,ALABAMAAMUNIVERSITY,False
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008,UNIVERSITYOFALABAMAATBIRMINGHAM,True
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589,AMRIDGEUNIVERSITY,False
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331,UNIVERSITYOFALABAMAINHUNTSVILLE,True
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308,ALABAMASTATEUNIVERSITY,False
5,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487-0166,Southern Association of Colleges and Schools C...,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,...,0.0073,0.2431,0.6817,0.0679,0.0142,0.2842,0.4599,0.2416,THEUNIVERSITYOFALABAMA,False
6,100760,100700,1007,Central Alabama Community College,Alexander City,AL,35010,Southern Association of Colleges and Schools C...,www.cacc.edu,https://www.cacc.edu/net-price-calculator/,...,0.0142,0.3794,0.2206,0.3858,0.0092,0.3258,0.2769,0.3881,CENTRALALABAMACOMMUNITYCOLLEGE,False
7,100812,100800,1008,Athens State University,Athens,AL,35611,Southern Association of Colleges and Schools C...,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,...,0.0109,0.1797,0.649,0.1604,0.0181,0.2112,0.4741,0.2966,ATHENSSTATEUNIVERSITY,False
8,100830,831000,8310,Auburn University at Montgomery,Montgomery,AL,36117-3596,Southern Association of Colleges and Schools C...,www.aum.edu,www.aum.edu/current-students/financial-informa...,...,0.0134,0.4208,0.327,0.2388,0.0289,0.3737,0.2352,0.3622,AUBURNUNIVERSITYATMONTGOMERY,False
9,100858,100900,1009,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,www.auburn.edu,https://www.auburn.edu/admissions/costcalc/fre...,...,0.0062,0.2026,0.7405,0.0506,0.0143,0.3829,0.4571,0.1457,AUBURNUNIVERSITY,True
10,100937,101200,1012,Birmingham Southern College,Birmingham,AL,35254,Southern Association of Colleges and Schools C...,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,...,0.0031,0.3303,0.6319,0.0348,NaN,NaN,NaN,NaN,BIRMINGHAMSOUTHERNCOLLEGE,False
11,101028,1218200,12182,Chattahoochee Valley Community College,Phenix City,AL,36869,Southern Association of Colleges and Schools C...,www.cv.edu,www.cv.edu/about/consumer-information/,...,0.0155,0.5959,0.2216,0.167,0.0067,0.5705,0.1678,0.255,CHATTAHOOCHEEVALLEYCOMMUNITYCOLLEGE,False
12,101073,1055400,10554,Concordia College Alabama,Selma,AL,36701,NaN,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,...,0.006,0.2376,0.1037,0.6526,0,0.2075,0.0094,0.783,CONCORDIACOLLEGEALABAMA,False
13,101116,1303906,13039,South University-Montgomery,Montgomery,AL,36116,Southern Association of Colleges and Schools C...,www.southuniversity.edu/montgomery#location=Mo...,www.southuniversity.edu/montgomery/net-price-c...,...,0,0.1263,0.2184,0.6553,0.0035,0.0804,0.2308,0.6853,SOUTHUNIVERSITYMONTGOMERY,False
14,101143,101500,1015,Enterprise State Community College,Enterprise,AL,36330-1300,Southern Association of Colleges and Schools C...,www.escc.edu,https://www.escc.edu/netprice/npcalc.htm,...,0.0095,0.3663,0.3104,0.3138,0.004,0.4113,0.1707,0.414,ENTERPRISESTATECOMMUNITYCOLLEGE,False
15,101161,106000,1060,Coastal Alabama Community College,Bay Minette,AL,36507-2698,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.0119,0.5981,0.2845,0.1056,0.019,0.5704,0.2838,0.1268,COASTALALABAMACOMMUNITYCOLLEGE,False
16,101189,100300,1003,Faulkner University,Montgomery,AL,36109-3390,Southern Association of Colleges and Schools C...,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,...,0.0057,0.3406,0.4638,0.19,0.0112,0.3825,0.3582,0.2481,FAULKNERUNIVERSITY,True
17,101240,101700,1017,Gadsden State Community College,Gadsden,AL,35903,Southern Association of Colleges and Schools C...,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,...,0.0215,0.1641,0.2742,0.5402,0.0835,0.1191,0.2338,0.5636,GADSDENSTATECOMMUNITYCOLLEGE,False
18,101277,4187200,41872,New Beginning College of Cosmetology,Albertville,AL,35951,National Accrediting Commission of Career Arts...,www.nbccosmetology.com,nbccosmetology.com/sa/nbc_zonemap/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEWBEGINNINGCOLLEGEOFCOSMETOLOGY,False
19,101286,101800,1018,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,Southern Association of Colleges and Schools C...,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,...,0.0221,0.2986,0.2993,0.3799,0.043,0.2557,0.2743,0.427,GEORGECWALLACECOMMUNITYCOLLEGEDOTHAN,False
20,101295,787100,7871,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,Southern Association of Colleges and Schools C...,www.wallacestate.edu,www.wallacestate.edu/Financial-Aid/Net-Price-C...,...,0.0084,0.2639,0.3458,0.3818,0.0103,0.374,0.2665,0.3492,GEORGECWALLACESTATECOMMUNITYCOLLEGEHANCEVILLE,False
21,101301,569900,5699,George C Wallace State Community College-Selma,Selma,AL,36703-2808,Southern Association of Colleges and Schools C...,www.wccs.edu,www.wccs.edu/financial-aid/about-financial-aid/,...,0.1991,0.1513,0.3276,0.3221,0.1536,0.1348,0.2102,0.5013,GEORGECWALLACESTATECOMMUNITYCOLLEGESELMA,False
22,101365,962107,9621,Herzing University-Birmingham,Birmingham,AL,35209,Higher Learning Commission,https://www.herzing.edu/,https://www.herzing.edu/tuition-financial-aid/...,...,0,0.1046,0.634,0.2614,0,0.1685,0.3641,0.4674,HERZINGUNIVERSITYBIRMINGHAM,False
23,101435,101900,1019,Huntingdon College,Montgomery,AL,36106-2148,Southern Association of Colleges and Schools C...,www.huntingdon.edu,hawk.huntingdon.edu/oiac/netpricecalculator/np...,...,0.0032,0.3946,0.4628,0.1395,0.0036,0.208,0.5985,0.1898,HUNTINGDONCOLLEGE,False
24,101453,2199700,21997,Heritage Christian University,Florence,AL,35630-9977,Association for Bibical Higher Educaiton,www.hcu.edu,www.hcu.edu/netpricecalculator/,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,0,0,0.1333,0.8667,HERITAGECHRISTIANUNIVERSITY,False
25,101462,526000,5260,J. F. Drake State Community and Technical College,Huntsville,AL,35811,Southern Association of Colleges and Schools C...,www.drakestate.edu,www.drakestate.edu/admissions/net_price_calcul...,...,0.0054,0.3074,0.3243,0.3629,0.0038,0.3094,0.2541,0.4327,JFDRAKESTATECOMMUNITYANDTECHNICALCOLLEGE,False
26,101471,3002500,30025,J F Ingram State Technical College,Deatsville,AL,36022,Council on Occupational Education,www.istc.edu,nces.ed.gov/ipeds/netpricecalculator/Npc_2.aspx,...,0.004,0,0.4279,0.5681,0.0097,0,0.2379,0.7524,JFINGRAMSTATETECHNICALCOLLEGE,False
27,101480,102000,1020,Jacksonville State University,Jacksonville,AL,36265,Southern Association of Colleges and Schools C...,www.jsu.edu/,www.jsu.edu/finaid/,...,0.0247,0,0.3965,0.5787,0.0219,0,0.48,0.4981,JACKSONVILLESTATEUNIVERSITY,True
28,101499,106010,1060,Jefferson Davis Community College,Brewton,AL,36426,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.031,0.1742,0.3703,0.4245,0.0426,0.1632,0.3386,0.4555,JEFFERSONDAVISCOMMUNITYCOLLEGE,False
29,101505,102200,1022,Jefferson State Community College,Birmingham,AL,35215-3098,Southern Association of Colleges and Schools C...,www.jeffersonstate.edu/,www.jeffersonstate.edu/financial-aid/net-price...,...,0.0266,0.4977,0.193,0.2827,0.0191,0.5436,0.1019,0.3354,JEFFERSONSTATECOMMUNITYCOLLEGE,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7028,47503301,4208601,42086,Relay Graduate School of Education - Newark,Newark,NJ,7102,Middle States Commission on Higher Education,relay.edu/location/relay-newark,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNEWARK,False
7029,47503302,4208602,42086,Relay Graduate School of Education - New Orleans,New Orleans,LA,70112,Middle States Commission on Higher Education,relay.edu/location/relay-new-orleans,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNEWORLEANS,False
7030,47503303,4208605,42086,Relay Graduate School of Education - Delaware,Wilmington,DE,19801,Middle States Commission on Higher Education,relay.edu/location/relay-delaware,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDELAWARE,False
7031,47503304,4208606,42086,Relay Graduate School of Education - Memphis,Memphis,TN,38104,Middle States Commission on Higher Education,relay.edu/location/relay-memphis,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONMEMPHIS,False
7032,47503305,4208603,42086,Relay Graduate School of Education - Houston,Houston,TX,770744906,Middle States Commission on Higher Education,relay.edu/location/relay-houston,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONHOUSTON,False
7033,47503306,4208604,42086,Relay Graduate School of Education - Chicago,Chicago,IL,606324906,Middle States Commission on Higher Education,relay.edu/location/relay-chicago,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONCHICAGO,False
7034,47503307,4208607,42086,Relay Graduate School of Education - Baton Rouge,Baton Rouge,LA,708114906,Middle States Commission on Higher Education,relay.edu/location/relay-baton-rouge,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONBATONROUGE,False
7035,47503308,4208608,42086,Relay Graduate School of Education - Philadelp...,Philadelphia,PA,191224906,Middle States Commission on Higher Education,relay.edu/location/relay-philadelphia-camden,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONPHILADELPHIACAMDEN,False
7036,47503309,4208609,42086,Relay Graduate School of Education - Denver,Denver,CO,802112534,Middle States Commission on Higher Education,relay.edu/location/relay-denver,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDENVER,False
7037,47503310,4208610,42086,Relay Graduate School of Education - Nashville,Nashville,TN,372075155,Middle States Commission on Higher Education,relay.edu/location/relay-nashville,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNASHVILLE,False
7038,47503311,4208611,42086,Relay Graduate School of Education - San Antonio,San Antonio,TX,782155155,Middle States Commission on Higher Education,relay.edu/location/relay-san-antonio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONSANANTONIO,False
7039,47503312,4208612,42086,Relay Graduate School of Education - Dallas-Fo...,Dallas,TX,752075155,Middle States Commission on Higher Education,relay.edu/location/relay-dallas-fort-worth,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDALLASFORTWORTH,False
7040,47503313,4208613,42086,Relay Graduate School of Education - Washingto...,Washington,DC,200375155,Middle States Commission on Higher Education,relay.edu/location/relay-washington-dc,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONWASHINGTONDC,False
7041,47647001,4088301,40883,WestMed College - Merced,Merced,CA,953400000,NaN,www.westmedcollege.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WESTMEDCOLLEGEMERCED,False
7042,47662901,4189101,41891,Salon Institute - Columbus Campus,Lewis Center,OH,430359153,National Accrediting Commission of Career Arts...,www.saloninstitute.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SALONINSTITUTECOLUMBUSCAMPUS,False
7043,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,94608,NaN,usa.sae.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SAEINSTITUTEOFTECHNOLOGYSANFRANCISCO,False
7044,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,662102786,Higher Learning Commission,rasmussen.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RASMUSSENCOLLEGEOVERLANDPARK,False
7045,48079001,4218901,42189,Rocky Vista University - Southern Utah,Ivins,UT,847386756,Higher Learning Commission,www.rvu.edu/rvu-su/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ROCKYVISTAUNIVERSITYSOUTHERNUTAH,False
7046,48092101,4220001,42200,Designer Barber & Stylist School -,Springdale,AR,727620990,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESIGNERBARBERSTYLISTSCHOOL,False
7047,48133101,4213501,42135,Sharp Edgez Barber Institute - Buffalo,Buffalo,NY,142170000,Council on Occupational Education,www.sharpedgezbarberinstitute.com,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SHARPEDGEZBARBERINSTITUTEBUFFALO,False
7048,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,44143,Accrediting Council for Continuing Education &...,nptiohio.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NATIONALPERSONALTRAININGINSTITUTEOFCLEVELAND,False
7049,48305401,4224601,42246,Barber School of Pittsburgh - Ambridge,Ambridge,PA,150030000,NaN,www.bsp.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BARBERSCHOOLOFPITTSBURGHAMBRIDGE,False
7050,48312401,108131,1081,Arizona State University at Tucson,Tucson,AZ,857454284,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATTUCSON,False
7051,48312402,108161,1081,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,864036877,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYASUCOLLEGESATLAKEHAVASUCITY,False
7052,48312403,108162,1081,Arizona State University at The Gila Valley,Thatcher,AZ,855525545,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATTHEGILAVALLEY,False
7053,48312404,108163,1081,Arizona State University at Yuma,Yuma,AZ,853656900,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATYUMA,False
7054,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,Accrediting Council for Independent Colleges a...,www.bamasf.com/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BAYAREAMEDICALACADEMYSANJOSESATELLITELOCATION,False
7055,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,935340000,Accrediting Council for Continuing Education &...,www.hdmc.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HIGHDESERTMEDICALCOLLEGE,False
7056,48778201,4221501,42215,BCI - Malden,Malden,MA,21480000,NaN,bostoncareer.org,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BCIMALDEN,False
7057,49005401,4182601,41826,Health Career Institute- Lauderdale Lakes,Lauderdale Lakes,FL,333137268,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HEALTHCAREERINSTITUTELAUDERDALELAKES,False

In [25]:
UPINSTN=[]
for index,row in combo_school_df.iterrows():
    if row["Online"]==True:
        UPINSTN.append(row["UP_INSTNM"])
#         print(row["UP_INSTNM"])
#     elif row["Online"] != True:
#         row["Online"] = False

In [26]:
#determine how many schools made to list
len(UPINSTN)

476

# Joining All Data with Zipcode Data

In [27]:
#import mean/median household income per zipcode data
mean_zip = "Resources/MeanZIP-3.csv"
mean_zip_df = pd.read_csv(mean_zip)
mean_zip_df = mean_zip_df.rename(columns={'Zip':'ZIP'})
mean_zip_df["ZIP"]= mean_zip_df["ZIP"].astype(str) 
mean_zip_df.head()

    ZIP  Median    Mean     Pop
0  1001  56,663  66,688  16,445
1  1002  49,853  75,063  28,069
2  1003  28,462  35,121   8,491
3  1005  75,423  82,442   4,798
4  1007  79,076  85,802  12,962

In [28]:
#import average rental prices per zipcode data
zipcode_prices = "Resources/ZRI_zipcode.csv"
zipcode_df = pd.read_csv(zipcode_prices, encoding='latin-1')
zipcode_df = zipcode_df.rename(columns={'RegionName':'ZIP'})
zipcode_df.head()

,ZIP,State,Metro,County,City,SizeRank,Zri,MoM,QoQ,YoY,ZriRecordCnt
0,10025,NY,New York-Newark-Jersey City,New York County,New York,0,3458,-0.018729,-0.037305,-0.002884,22563
1,60657,IL,Chicago-Naperville-Elgin,Cook County,Chicago,1,1922,0.009984,0.013713,0.060706,32530
2,10023,NY,New York-Newark-Jersey City,New York County,New York,2,3799,-0.022136,-0.048585,0.035997,29247
3,77494,TX,Houston-The Woodlands-Sugar Land,Harris County,Katy,3,2174,0.009754,0.024988,-0.006852,31733
4,60614,IL,Chicago-Naperville-Elgin,Cook County,Chicago,4,2223,0.030120,0.072876,0.135342,33465

In [29]:
#merged both zipcode dataframes
zipcode_df["ZIP"]= zipcode_df["ZIP"].astype(str)
zip_joined_df = pd.merge(mean_zip_df, zipcode_df, on='ZIP', how='inner')
zip_joined_df = zip_joined_df[["ZIP", "Median", "Mean", "Zri"]]
zip_joined_df = zip_joined_df.rename(columns={"Median":"Median Household Income in ZIP", "Mean": "Mean Household Income in ZIP", "Zri":"Rental Prices in ZIP"})
zip_joined_df

,ZIP,Median Household Income in ZIP,Mean Household Income in ZIP,Rental Prices in ZIP
0,1001,"56,663","66,688",1586
1,1002,"49,853","75,063",2362
2,1005,"75,423","82,442",1541
3,1007,"79,076","85,802",1855
4,1008,"63,980","78,391",1556
5,1010,"75,625","80,919",1708
6,1011,"63,476","77,443",1449
7,1013,"36,578","46,179",1487
8,1020,"50,058","58,516",1509
9,1022,"50,440","60,797",1193
10,1026,"60,320","71,505",1981
11,1027,"58,573","66,613",1784
12,1028,"80,252","94,891",1938
13,1030,"71,106","81,727",1779
14,1034,"63,980","78,391",1765
15,1035,"69,911","73,973",2387
16,1036,"78,869","95,493",1918
17,1038,"53,939","72,430",2239
18,1040,"35,549","43,615",1476
19,1050,"62,097","70,566",1664
20,1053,"60,477","77,611",1954
21,1056,"63,318","72,027",1569
22,1057,"73,254","78,485",1510
23,1060,"48,069","67,478",2073
24,1062,"60,686","82,398",2062
25,1068,"77,396","81,314",1767
26,1071,"63,980","78,391",1563
27,1072,"67,831","86,678",2122
28,1073,"80,738","94,452",1965
29,1075,"63,053","76,027",1642
...,...,...,...,...
15701,99354,"63,383","74,924",1537
15702,99362,"85,482","109,330",1354
15703,99402,"57,091","77,979",1482
15704,99403,"42,707","53,596",1389
15705,99501,"50,916","67,858",1615
15706,99502,"83,147","102,678",1869
15707,99503,"44,239","56,864",1585
15708,99504,"69,475","76,829",1720
15709,99507,"87,103","98,407",1887
15710,99508,"56,889","70,221",1604
15711,99515,"79,312","100,588",2061
15712,99516,"138,809","163,032",2534
15713,99517,"75,489","92,976",1774
15714,99518,"80,565","84,279",1692
15715,99556,"49,806","59,116",1226
15716,99567,"95,305","102,582",2048
15717,99577,"94,376","107,567",2023
15718,99587,"67,983","97,125",1748
15719,99603,"51,299","66,322",1383
15720,99611,"60,548","70,660",1327
15721,99615,"60,983","74,908",1643
15722,99645,"73,230","85,057",1553
15723,99654,"67,856","78,784",1545
15724,99664,"57,915","73,180",1444
15725,99669,"59,494","74,328",1384
15726,99701,"49,058","59,439",1536
15727,99705,"79,720","84,752",1660
15728,99709,"75,763","90,739",1658
15729,99712,"78,699","96,148",1672
15730,99901,"62,507","72,490",1623

In [30]:
#clean up the zip column so that it is only the first five numbers
start, stop, step = 0, 5, 1
combo_school_df["ZIP"]= combo_school_df["ZIP"].str.slice(start, stop, step) 
combo_school_df

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP,UP_INSTNM,Online
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852,ALABAMAAMUNIVERSITY,False
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008,UNIVERSITYOFALABAMAATBIRMINGHAM,True
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589,AMRIDGEUNIVERSITY,False
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331,UNIVERSITYOFALABAMAINHUNTSVILLE,True
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308,ALABAMASTATEUNIVERSITY,False
5,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487,Southern Association of Colleges and Schools C...,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,...,0.0073,0.2431,0.6817,0.0679,0.0142,0.2842,0.4599,0.2416,THEUNIVERSITYOFALABAMA,False
6,100760,100700,1007,Central Alabama Community College,Alexander City,AL,35010,Southern Association of Colleges and Schools C...,www.cacc.edu,https://www.cacc.edu/net-price-calculator/,...,0.0142,0.3794,0.2206,0.3858,0.0092,0.3258,0.2769,0.3881,CENTRALALABAMACOMMUNITYCOLLEGE,False
7,100812,100800,1008,Athens State University,Athens,AL,35611,Southern Association of Colleges and Schools C...,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,...,0.0109,0.1797,0.649,0.1604,0.0181,0.2112,0.4741,0.2966,ATHENSSTATEUNIVERSITY,False
8,100830,831000,8310,Auburn University at Montgomery,Montgomery,AL,36117,Southern Association of Colleges and Schools C...,www.aum.edu,www.aum.edu/current-students/financial-informa...,...,0.0134,0.4208,0.327,0.2388,0.0289,0.3737,0.2352,0.3622,AUBURNUNIVERSITYATMONTGOMERY,False
9,100858,100900,1009,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,www.auburn.edu,https://www.auburn.edu/admissions/costcalc/fre...,...,0.0062,0.2026,0.7405,0.0506,0.0143,0.3829,0.4571,0.1457,AUBURNUNIVERSITY,True
10,100937,101200,1012,Birmingham Southern College,Birmingham,AL,35254,Southern Association of Colleges and Schools C...,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,...,0.0031,0.3303,0.6319,0.0348,NaN,NaN,NaN,NaN,BIRMINGHAMSOUTHERNCOLLEGE,False
11,101028,1218200,12182,Chattahoochee Valley Community College,Phenix City,AL,36869,Southern Association of Colleges and Schools C...,www.cv.edu,www.cv.edu/about/consumer-information/,...,0.0155,0.5959,0.2216,0.167,0.0067,0.5705,0.1678,0.255,CHATTAHOOCHEEVALLEYCOMMUNITYCOLLEGE,False
12,101073,1055400,10554,Concordia College Alabama,Selma,AL,36701,NaN,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,...,0.006,0.2376,0.1037,0.6526,0,0.2075,0.0094,0.783,CONCORDIACOLLEGEALABAMA,False
13,101116,1303906,13039,South University-Montgomery,Montgomery,AL,36116,Southern Association of Colleges and Schools C...,www.southuniversity.edu/montgomery#location=Mo...,www.southuniversity.edu/montgomery/net-price-c...,...,0,0.1263,0.2184,0.6553,0.0035,0.0804,0.2308,0.6853,SOUTHUNIVERSITYMONTGOMERY,False
14,101143,101500,1015,Enterprise State Community College,Enterprise,AL,36330,Southern Association of Colleges and Schools C...,www.escc.edu,https://www.escc.edu/netprice/npcalc.htm,...,0.0095,0.3663,0.3104,0.3138,0.004,0.4113,0.1707,0.414,ENTERPRISESTATECOMMUNITYCOLLEGE,False
15,101161,106000,1060,Coastal Alabama Community College,Bay Minette,AL,36507,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.0119,0.5981,0.2845,0.1056,0.019,0.5704,0.2838,0.1268,COASTALALABAMACOMMUNITYCOLLEGE,False
16,101189,100300,1003,Faulkner University,Montgomery,AL,36109,Southern Association of Colleges and Schools C...,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,...,0.0057,0.3406,0.4638,0.19,0.0112,0.3825,0.3582,0.2481,FAULKNERUNIVERSITY,True
17,101240,101700,1017,Gadsden State Community College,Gadsden,AL,35903,Southern Association of Colleges and Schools C...,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,...,0.0215,0.1641,0.2742,0.5402,0.0835,0.1191,0.2338,0.5636,GADSDENSTATECOMMUNITYCOLLEGE,False
18,101277,4187200,41872,New Beginning College of Cosmetology,Albertville,AL,35951,National Accrediting Commission of Career Arts...,www.nbccosmetology.com,nbccosmetology.com/sa/nbc_zonemap/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEWBEGINNINGCOLLEGEOFCOSMETOLOGY,False
19,101286,101800,1018,George C Wallace Community College-Dothan,Dothan,AL,36303,Southern Association of Colleges and Schools C...,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,...,0.0221,0.2986,0.2993,0.3799,0.043,0.2557,0.2743,0.427,GEORGECWALLACECOMMUNITYCOLLEGEDOTHAN,False
20,101295,787100,7871,George C Wallace State Community College-Hance...,Hanceville,AL,35077,Southern Association of Colleges and Schools C...,www.wallacestate.edu,www.wallacestate.edu/Financial-Aid/Net-Price-C...,...,0.0084,0.2639,0.3458,0.3818,0.0103,0.374,0.2665,0.3492,GEORGECWALLACESTATECOMMUNITYCOLLEGEHANCEVILLE,False
21,101301,569900,5699,George C Wallace State Community College-Selma,Selma,AL,36703,Southern Association of Colleges and Schools C...,www.wccs.edu,www.wccs.edu/financial-aid/about-financial-aid/,...,0.1991,0.1513,0.3276,0.3221,0.1536,0.1348,0.2102,0.5013,GEORGECWALLACESTATECOMMUNITYCOLLEGESELMA,False
22,101365,962107,9621,Herzing University-Birmingham,Birmingham,AL,35209,Higher Learning Commission,https://www.herzing.edu/,https://www.herzing.edu/tuition-financial-aid/...,...,0,0.1046,0.634,0.2614,0,0.1685,0.3641,0.4674,HERZINGUNIVERSITYBIRMINGHAM,False
23,101435,101900,1019,Huntingdon College,Montgomery,AL,36106,Southern Association of Colleges and Schools C...,www.huntingdon.edu,hawk.huntingdon.edu/oiac/netpricecalculator/np...,...,0.0032,0.3946,0.4628,0.1395,0.0036,0.208,0.5985,0.1898,HUNTINGDONCOLLEGE,False
24,101453,2199700,21997,Heritage Christian University,Florence,AL,35630,Association for Bibical Higher Educaiton,www.hcu.edu,www.hcu.edu/netpricecalculator/,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,0,0,0.1333,0.8667,HERITAGECHRISTIANUNIVERSITY,False
25,101462,526000,5260,J. F. Drake State Community and Technical College,Huntsville,AL,35811,Southern Association of Colleges and Schools C...,www.drakestate.edu,www.drakestate.edu/admissions/net_price_calcul...,...,0.0054,0.3074,0.3243,0.3629,0.0038,0.3094,0.2541,0.4327,JFDRAKESTATECOMMUNITYANDTECHNICALCOLLEGE,False
26,101471,3002500,30025,J F Ingram State Technical College,Deatsville,AL,36022,Council on Occupational Education,www.istc.edu,nces.ed.gov/ipeds/netpricecalculator/Npc_2.aspx,...,0.004,0,0.4279,0.5681,0.0097,0,0.2379,0.7524,JFINGRAMSTATETECHNICALCOLLEGE,False
27,101480,102000,1020,Jacksonville State University,Jacksonville,AL,36265,Southern Association of Colleges and Schools C...,www.jsu.edu/,www.jsu.edu/finaid/,...,0.0247,0,0.3965,0.5787,0.0219,0,0.48,0.4981,JACKSONVILLESTATEUNIVERSITY,True
28,101499,106010,1060,Jefferson Davis Community College,Brewton,AL,36426,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.031,0.1742,0.3703,0.4245,0.0426,0.1632,0.3386,0.4555,JEFFERSONDAVISCOMMUNITYCOLLEGE,False
29,101505,102200,1022,Jefferson State Community College,Birmingham,AL,35215,Southern Association of Colleges and Schools C...,www.jeffersonstate.edu/,www.jeffersonstate.edu/financial-aid/net-price...,...,0.0266,0.4977,0.193,0.2827,0.0191,0.5436,0.1019,0.3354,JEFFERSONSTATECOMMUNITYCOLLEGE,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7028,47503301,4208601,42086,Relay Graduate School of Education - Newark,Newark,NJ,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-newark,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNEWARK,False
7029,47503302,4208602,42086,Relay Graduate School of Education - New Orleans,New Orleans,LA,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-new-orleans,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNEWORLEANS,False
7030,47503303,4208605,42086,Relay Graduate School of Education - Delaware,Wilmington,DE,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-delaware,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDELAWARE,False
7031,47503304,4208606,42086,Relay Graduate School of Education - Memphis,Memphis,TN,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-memphis,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONMEMPHIS,False
7032,47503305,4208603,42086,Relay Graduate School of Education - Houston,Houston,TX,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-houston,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONHOUSTON,False
7033,47503306,4208604,42086,Relay Graduate School of Education - Chicago,Chicago,IL,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-chicago,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONCHICAGO,False
7034,47503307,4208607,42086,Relay Graduate School of Education - Baton Rouge,Baton Rouge,LA,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-baton-rouge,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONBATONROUGE,False
7035,47503308,4208608,42086,Relay Graduate School of Education - Philadelp...,Philadelphia,PA,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-philadelphia-camden,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONPHILADELPHIACAMDEN,False
7036,47503309,4208609,42086,Relay Graduate School of Education - Denver,Denver,CO,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-denver,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDENVER,False
7037,47503310,4208610,42086,Relay Graduate School of Education - Nashville,Nashville,TN,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-nashville,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONNASHVILLE,False
7038,47503311,4208611,42086,Relay Graduate School of Education - San Antonio,San Antonio,TX,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-san-antonio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONSANANTONIO,False
7039,47503312,4208612,42086,Relay Graduate School of Education - Dallas-Fo...,Dallas,TX,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-dallas-fort-worth,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONDALLASFORTWORTH,False
7040,47503313,4208613,42086,Relay Graduate School of Education - Washingto...,Washington,DC,NaN,Middle States Commission on Higher Education,relay.edu/location/relay-washington-dc,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RELAYGRADUATESCHOOLOFEDUCATIONWASHINGTONDC,False
7041,47647001,4088301,40883,WestMed College - Merced,Merced,CA,NaN,NaN,www.westmedcollege.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WESTMEDCOLLEGEMERCED,False
7042,47662901,4189101,41891,Salon Institute - Columbus Campus,Lewis Center,OH,NaN,National Accrediting Commission of Career Arts...,www.saloninstitute.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SALONINSTITUTECOLUMBUSCAMPUS,False
7043,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,NaN,NaN,usa.sae.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SAEINSTITUTEOFTECHNOLOGYSANFRANCISCO,False
7044,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,NaN,Higher Learning Commission,rasmussen.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RASMUSSENCOLLEGEOVERLANDPARK,False
7045,48079001,4218901,42189,Rocky Vista University - Southern Utah,Ivins,UT,NaN,Higher Learning Commission,www.rvu.edu/rvu-su/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ROCKYVISTAUNIVERSITYSOUTHERNUTAH,False
7046,48092101,4220001,42200,Designer Barber & Stylist School -,Springdale,AR,NaN,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESIGNERBARBERSTYLISTSCHOOL,False
7047,48133101,4213501,42135,Sharp Edgez Barber Institute - Buffalo,Buffalo,NY,NaN,Council on Occupational Education,www.sharpedgezbarberinstitute.com,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SHARPEDGEZBARBERINSTITUTEBUFFALO,False
7048,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,NaN,Accrediting Council for Continuing Education &...,nptiohio.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NATIONALPERSONALTRAININGINSTITUTEOFCLEVELAND,False
7049,48305401,4224601,42246,Barber School of Pittsburgh - Ambridge,Ambridge,PA,NaN,NaN,www.bsp.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BARBERSCHOOLOFPITTSBURGHAMBRIDGE,False
7050,48312401,108131,1081,Arizona State University at Tucson,Tucson,AZ,NaN,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATTUCSON,False
7051,48312402,108161,1081,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,NaN,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYASUCOLLEGESATLAKEHAVASUCITY,False
7052,48312403,108162,1081,Arizona State University at The Gila Valley,Thatcher,AZ,NaN,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATTHEGILAVALLEY,False
7053,48312404,108163,1081,Arizona State University at Yuma,Yuma,AZ,NaN,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARIZONASTATEUNIVERSITYATYUMA,False
7054,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,NaN,Accrediting Council for Independent Colleges a...,www.bamasf.com/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BAYAREAMEDICALACADEMYSANJOSESATELLITELOCATION,False
7055,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,NaN,Accrediting Council for Continuing Education &...,www.hdmc.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HIGHDESERTMEDICALCOLLEGE,False
7056,48778201,4221501,42215,BCI - Malden,Malden,MA,NaN,NaN,bostoncareer.org,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BCIMALDEN,False
7057,49005401,4182601,41826,Health Career Institute- Lauderdale Lakes,Lauderdale Lakes,FL,NaN,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HEALTHCAREERINSTITUTELAUDERDALELAKES,False

In [37]:
#merge joined zipcode data into rest of the college school dataframe
final_df = pd.merge(combo_school_df, zip_joined_df, on='ZIP', how='left')
final_df = final_df[["INSTNM", "CITY", "STABBR", "ZIP", "ADM_RATE_ALL", "TUITIONFEE_IN", "TUITIONFEE_OUT", "MN_EARN_WNE_P10", "MD_EARN_WNE_P10", "GRAD_DEBT_MDN", "Online", "Median Household Income in ZIP", "Mean Household Income in ZIP", "Rental Prices in ZIP"]]
final_df = final_df.rename(columns={"INSTNM":"Institution", "CITY":"City", "STABBR":"State Abbreviation", "ADM_RATE_ALL":"Admissions Rate", "TUITIONFEE_IN":"Tuition In-State", "TUITIONFEE_OUT":"Tuition Out-of-State", "MN_EARN_WNE_P10":"Mean Earnings Post-10 Years", "MD_EARN_WNE_P10": "Median Earnings Post-10 Years", "GRAD_DEBT_MDN":"Median Debt for Post-grads"})

In [38]:
final_df = final_df.dropna()
final_df = final_df.reset_index()
final_df.index.name='id'
final_df

,index,Institution,City,State Abbreviation,ZIP,Admissions Rate,Tuition In-State,Tuition Out-of-State,Mean Earnings Post-10 Years,Median Earnings Post-10 Years,Median Debt for Post-grads,Online,Median Household Income in ZIP,Mean Household Income in ZIP,Rental Prices in ZIP
id,,,,,,,,,,,,,,,
0,4,Alabama State University,Montgomery,AL,36104,0.978661,11068.0,19396.0,30600,27700,31500,False,"21,269","32,968",704.0
1,8,Auburn University at Montgomery,Montgomery,AL,36117,0.825384,8020.0,17140.0,38000,33300,23363,False,"66,917","81,904",1206.0
2,16,Faulkner University,Montgomery,AL,36109,0.510064,20970.0,20970.0,40700,35400,22850,True,"51,093","62,532",898.0
3,22,Herzing University-Birmingham,Birmingham,AL,35209,0.794083,13850.0,13850.0,41600,37800,23139.5,False,"53,792","67,735",1894.0
4,23,Huntingdon College,Montgomery,AL,36106,0.559788,26400.0,26400.0,43600,39900,27000,False,"59,961","79,508",1078.0
5,24,Heritage Christian University,Florence,AL,35630,1.000000,11232.0,11232.0,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,False,"30,252","43,603",782.0
6,27,Jacksonville State University,Jacksonville,AL,36265,0.540216,8166.0,15582.0,38100,35800,23500,True,"37,638","48,082",880.0
7,37,University of Mobile,Mobile,AL,36613,0.470194,22210.0,22210.0,38700,35200,26579.5,False,"40,155","49,715",905.0
8,38,University of Montevallo,Montevallo,AL,35115,0.644547,12400.0,25030.0,36100,34200,24264,False,"39,872","56,778",1134.0
9,51,Spring Hill College,Mobile,AL,36608,0.456812,37584.0,37584.0,51300,45100,PrivacySuppressed,False,"49,568","74,790",1079.0
10,52,Stillman College,Tuscaloosa,AL,35401,0.481163,10792.0,10792.0,33700,28200,33500,False,"17,806","26,527",1098.0
11,59,University of Alaska Anchorage,Anchorage,AK,99508,0.828310,6690.0,19494.0,51200,45400,17833.5,False,"56,889","70,221",1604.0
12,63,Alaska Pacific University,Anchorage,AK,99508,0.860000,20760.0,20760.0,45300,40200,19500,False,"56,889","70,221",1604.0
13,89,Embry-Riddle Aeronautical University-Prescott,Prescott,AZ,86301,0.737117,34662.0,34662.0,70300,66200,24250,False,"43,823","63,229",1648.0
14,92,Grand Canyon University,Phoenix,AZ,85017,0.669212,17050.0,17050.0,58500,52700,18750,True,"31,956","38,214",1198.0
15,106,Prescott College,Prescott,AZ,86301,0.952618,30501.0,30501.0,34300,33200,19208.5,True,"43,823","63,229",1648.0
16,113,Arizona Christian University,Phoenix,AZ,85032,0.644407,24958.0,24958.0,34900,32200,18850,False,"51,731","62,497",1489.0
17,118,University of Arkansas at Little Rock,Little Rock,AR,72204,0.746325,8998.0,21208.0,39500,34900,19750,False,"33,627","40,601",791.0
18,126,University of Arkansas,Fayetteville,AR,72701,0.659636,9062.0,24308.0,52700,44900,21500,True,"37,482","51,603",1296.0
19,129,Arkansas State University-Main Campus,Jonesboro,AR,72401,0.660215,8478.0,14778.0,36600,32200,19500,False,"36,445","49,528",985.0
20,130,Arkansas Tech University,Russellville,AR,72801,0.947463,7104.0,12528.0,38600,34100,18000,False,"34,558","47,671",854.0
21,133,Baptist Health College Little Rock,Little Rock,AR,72210,0.687500,9867.0,9867.0,48100,47200,11000,False,"51,780","67,591",1281.0
22,136,Central Baptist College,Conway,AR,72034,0.675462,15750.0,15750.0,43000,35300,28250,False,"47,433","63,561",1189.0
23,147,Hendrix College,Conway,AR,72032,0.797952,44070.0,44070.0,44500,39700,27000,False,"44,172","55,816",1001.0
24,150,John Brown University,Siloam Springs,AR,72761,0.757930,26144.0,26144.0,55400,45800,20500,True,"39,835","51,578",1048.0
25,161,University of the Ozarks,Clarksville,AR,72830,0.891457,23750.0,23750.0,38600,33900,20500,False,"29,754","42,109",809.0
26,162,University of Arkansas Community College-Morri...,Morrilton,AR,72110,0.750560,3092.0,4004.0,31600,27500,6822,False,"34,721","47,218",863.0
27,185,American Academy of Dramatic Arts-Los Angeles,Los Angeles,CA,90028,0.788372,34170.0,34170.0,38200,32700,12000,False,"31,718","45,197",2868.0
28,193,Art Center College of Design,Pasadena,CA,91103,0.703567,42008.0,42008.0,62300,53600,31624,False,"60,526","77,853",2835.0
29,196,Azusa Pacific University,Azusa,CA,91702,0.601186,37506.0,37506.0,55900,51100,23092,False,"55,942","64,390",2340.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,5867,Harrison College-Morrisville,Morrisville,NC,27560,1.000000,16500.0,16500.0,26400,24700,24667,False,"79,226","96,652",1591.0
1089,5893,Los Angeles Pacific University,San Dimas,CA,91773,0.601186,10200.0,10200.0,55900,51100,23092,False,"76,397","89,747",2578.0
1090,5946,Chamberlain University-Georgia,Atlanta,GA,30342,0.556291,19375.0,19375.0,60400,58400,22893.5,False,"79,736","129,650",3016.0
1091,5947,Chamberlain University-Indiana,Indianapolis,IN,46240,0.556291,19375.0,19375.0,60400,58400,22893.5,False,"58,821","84,720",1493.0
1092,6037,Mercyhurst University-North East Campus,North East,PA,16428,0.699156,18450.0,18450.0,44200,40300,26850,False,"47,693","56,797",1083.0
1093,6038,Warner Pacific University Professional and Gra...,Portland,OR,97266,0.953237,8520.0,8520.0,45200,41000,25922,False,"41,274","48,310",1683.0
1094,6138,Middle Georgia State University,Macon,GA,31206,0.939682,3924.0,11092.0,35000,31500,18420,False,"27,999","37,535",702.0
1095,6154,DeVry College of New York,New York,NY,10016,0.940143,18020.0,18020.0,50300,44100,35766.5,False,"96,760","144,872",3518.0
1096,6155,DeVry University-Arizona,Phoenix,AZ,85021,0.940143,17188.0,17188.0,50300,44100,35766.5,False,"44,596","59,872",1401.0
1097,6156,DeVry University-California,Pomona,CA,91768,0.940143,17700.0,17700.0,50300,44100,35766.5,False,"52,262","54,887",2229.0
1098,6157,DeVry University-Colorado,Westminster,CO,80234,0.940143,17380.0,17380.0,50300,44100,35766.5,False,"64,407","82,637",2125.0
1099,6158,DeVry University-Florida,Miramar,FL,33027,0.940143,17732.0,17732.0,50300,44100,35766.5,False,"74,988","87,548",2033.0
1100,6159,DeVry University-Georgia,Decatur,GA,30030,0.940143,17636.0,17636.0,50300,44100,35766.5,False,"71,913","86,991",2285.0
1101,6160,DeVry University-Illinois,Chicago,IL,60618,0.940143,17316.0,17316.0,50300,44100,35766.5,False,"58,006","74,577",1915.0
1102,6161,DeVry University-Indiana,Merrillville,IN,46410,0.940143,18148.0,18148.0,50300,44100,35766.5,False,"48,460","56,193",1285.0
1103,6162,DeVry University-Missouri,Kansas City,MO,64131,0.940143,17252.0,17252.0,50300,44100,35766.5,False,"45,346","56,294",1183.0
1104,6163,DeVry University-Nevada,Henderson,NV,89074,0.940143,17572.0,17572.0,50300,44100,35766.5,False,"71,088","91,237",1547.0
1105,6165,DeVry University-North Carolina,Charlotte,NC,28273,0.940143,18052.0,18052.0,50300,44100,35766.5,False,"51,769","60,999",1441.0
1106,6166,DeVry University-Ohio,Columbus,OH,43209,0.940143,17476.0,17476.0,50300,44100,35766.5,False,"66,187","85,559",1603.0
1107,6167,DeVry University-Oklahoma,Oklahoma City,OK,73116,0.940143,17732.0,17732.0,50300,44100,35766.5,False,"66,665","121,483",1349.0
1108,6168,DeVry University-Pennsylvania,Ft. Washington,PA,19034,0.940143,17572.0,17572.0,50300,44100,35766.5,False,"106,374","143,924",2771.0
1109,6169,DeVry University-Tennessee,Nashville,TN,37211,0.940143,17828.0,17828.0,50300,44100,35766.5,False,"44,817","53,732",1574.0
1110,6170,DeVry University-Texas,Irving,TX,75063,0.940143,17540.0,17540.0,50300,44100,35766.5,False,"73,463","92,978",2346.0
1111,6171,DeVry University-Virginia,Arlington,VA,22202,0.940143,17572.0,17572.0,50300,44100,35766.5,False,"101,770","117,577",2825.0
1112,6180,Arizona College-Mesa,Mesa,AZ,85201,0.500000,19345.0,19345.0,26400,25600,9500,False,"40,225","50,710",1297.0
1113,6187,Arizona State University-Skysong,Scottsdale,AZ,85257,0.778069,9222.0,15691.0,55500,47700,20000,False,"49,327","58,485",1737.0
1114,6286,University of North Texas at Dallas,Dallas,TX,75241,0.739717,7848.0,20088.0,49300,45000,10232,False,"30,498","37,828",1291.0
1115,6300,West Coast University-Miami,Doral,FL,33178,0.944444,21331.0,21331.0,67700,54900,33937.5,False,"67,121","82,824",2256.0
1116,6614,Troy University-Phenix City Campus,Phenix City,AL,36869,0.881227,8692.0,16276.0,41100,37000,25000,False,"32,620","40,795",843.0
1117,6616,Troy University-Dothan Campus,Dothan,AL,36303,0.881227,8692.0,16276.0,41100,37000,25000,False,"42,612","56,976",996.0

# Reflect Tables into SQLAlchemy ORM

In [49]:
engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/ETL_project')
connection = engine.connect()

In [50]:
Base = automap_base()
Base.prepare(engine, reflect = True)
inspector = inspect(engine)

session = Session(engine)

In [51]:
engine.table_names()

['schools']

In [52]:
final_df.to_sql(name='schools', con=engine, if_exists='append', index=False)